/* =====================================================================
   Survey Atlas · 数据文件
   ---------------------------------------------------------------------
   巡天数据集中在这里，改数据不用碰 app.js：
     REG     9 个波段/类型域（label + hex，与 style.css 的 --c-* 保持一致）
     SURVEYS 巡天主数据（d = 数据档案：p 产品 / a 获取 / c 节奏 / v 规模）
     TIMELINE 发布日历
     GUIDE   选型指南
     SOURCES 来源列表
   数值键 areaN/depthN/nN/rN 供表格排序；≈ 为约值，⚠ 为待复核项。
   ===================================================================== */

const REG = {
  img:   {label:'成像·光学', color:'var(--c-img)',   hex:'#1f6fd0'},
  ir:    {label:'成像·红外', color:'var(--c-ir)',    hex:'#c2571a'},
  uv:    {label:'紫外',      color:'var(--c-uv)',    hex:'#7048c8'},
  xspec: {label:'光谱·河外', color:'var(--c-xspec)', hex:'#0e8a5c'},
  gspec: {label:'光谱·银河系',color:'var(--c-gspec)', hex:'#d5336c'},
  radio: {label:'射电',      color:'var(--c-radio)', hex:'#d03c3c'},
  xray:  {label:'X 射线',   color:'var(--c-xray)',  hex:'#47617f'},
  time:  {label:'时域',      color:'var(--c-time)',  hex:'#a16e03'},
  astro: {label:'天测',      color:'var(--c-astro)', hex:'#0f7f9e'},
};

const SURVEYS = [
/* ---------------- 光学成像 ---------------- */
{id:'sdss', name:'SDSS', en:'Sloan Digital Sky Survey', reg:['img','xspec'],
 d:{p:'五带成像 + photo 测光星表(≈10 亿源) + 400 多万条光谱', a:'SkyServer(SQL/CasJobs)、SciServer、SAS 批量下载', c:'成像多次通过；光谱单次曝光', v:'星表 GB 级、光谱数百万条 FITS'},
 status:'done', facility:'Apache Point 2.5 m（新墨西哥）', dr:'DR17（成像终版）', drDate:'2021-12',
 area:'14,555 deg²（北天，|b|≳15°）', areaN:14555,
 bands:'u g r i z',
 depth:'5σ ≈ 22.0 / 23.0 / 23.1 / 22.4 / 20.7', depthN:23.1,
 resAng:'≈1.3″/像素；0.8–1.5″ 视宁度', nsrc:'约 10 亿测光源 + 家族累计 400 万+ 光谱', nN:9,
 spec:'光谱 R≈1,800–2,600（BOSS 3,600–10,400 Å）', rN:2000,
 sci:'河外星系巡天奠基者：测光红移、QSO、星系形态；与 Gaia 交叉匹配的基准框架。',
 links:[['官网 dr17','https://www.sdss.org/dr17/'],['数据获取','https://www.sdss.org/dr17/data_access/'],['SkyServer','https://skyserver.sdss.org/'],['CASJobs','https://skyserver.sdss.org/casjobs/']],
 paper:['成像与巡天总览（York et al. 2000）','https://arxiv.org/abs/astro-ph/0006396'],
 note:'测光部分已定版；光谱持续在 SDSS-V 中更新（见 SDSS-V 卡）。u 波段浅、南天覆盖少，南天用 DES/Legacy/SkyMapper 补。'},

{id:'ps1', name:'Pan-STARRS PS1', en:'Pan-STARRS1 3π Survey', reg:['img','time'],
 d:{p:'grizy 叠加图像 + 星表(3π ≈30 亿检测)', a:'MAST PS1 切图/API、VizieR、Data Lab', c:'每带平均 12 次曝光叠加(3π)', v:'原始 ≈4 PB、产品数百 TB ⚠'},
 status:'done', facility:'Pan-STARRS1 1.8 m（夏威夷 Haleakala）', dr:'DR2', drDate:'2019-01',
 area:'3π sr ≈ 30,850 deg²（Dec > −30°）', areaN:30850,
 bands:'g r i z y',
 depth:'5σ 堆叠 ≈ 23.3 / 23.2 / 23.1 / 22.3 / 21.4', depthN:23.2,
 resAng:'1″/像素；≈1.2″ FWHM（堆叠）', nsrc:'≈30 亿检测（object 库，含历元数据）⚠', nN:9.5,
 sci:'北天全天 grizy 底图 + 时域（2010–2014 历元测光）；太阳系小天体主力。',
 links:[['MAST PS1 档案','https://outerspace.stsci.edu/panstarrs/'],['目录检索','https://catalogs.mast.stsci.edu/'],['巡天论文 (1612.05560)','https://arxiv.org/abs/1612.05560']],
 paper:['PS1 系统与巡天（Chambers et al. 2016）','https://arxiv.org/abs/1612.05560'],
 note:'DR2 含 DR1 全部内容并开放单历元测光/天测数据库。Medium-Deep 字段深 2–3 mag。南天 Dec<−30° 无覆盖。'},

{id:'des', name:'DES', en:'Dark Energy Survey', reg:['img','time'],
 d:{p:'grizY 图像 + 测光/形状星表 + SN/强透镜表', a:'DESC 数据库、LIneA、图像 cutout 服务', c:'Y1–Y6 分年释放(共 6 年)', v:'DR2 ≈7 亿源、图像 PB 级 ⚠'},
 status:'done', facility:'Blanco 4 m + DECam（智利 CTIO）', dr:'DR2（含 Y1–Y6 全部六年）', drDate:'2024',
 area:'≈5,000 deg²（南银帽）', areaN:5000,
 bands:'g r i z Y',
 depth:'堆叠 10σ ≈ 25.0 / 24.6 / 24.1 / 23.7 / 22.7 ⚠（Y6 口径）', depthN:24.6,
 resAng:'0.263″/像素；≈0.9″', nsrc:'≈7 亿源', nN:8.85,
 sci:'弱引力透镜、星系团、大尺度结构、超新星；南天深度测光标杆。',
 links:[['数据获取（官方）','https://www.darkenergysurvey.org/the-des-project/data-access/'],['NOIRLab Data Lab','https://datalab.noirlab.edu/'],['Y6 测光论文 (2501.05739)','https://arxiv.org/abs/2501.05739']],
 paper:['DES DR2（Abbott et al.，配套 Y6 数据集论文 arXiv:2501.05739）','https://arxiv.org/abs/2501.05739'],
 note:'DR2 为全部六年巡天数据；Y3 "Gold" 星表仍是很多论文的标准选择。与 KiDS 天区部分重叠、深度更深。'},

{id:'legacy', name:'DESI Legacy Imaging Surveys', en:'DECaLS + BASS + MzLS (+DES/DELVE 等)', reg:['img','ir'],
 d:{p:'g/r/z 叠加图像 + Tractor 测光星表', a:'legacysurvey.org(切图/表)、NERSC、Data Lab', c:'每区域 3–8 次访问叠加', v:'DR11 ≈40 亿源、几十 TB'},
 status:'run', facility:'Blanco 4 m DECam / Bok 2.3 m / Mayall 4 m（南北联合）', dr:'DR11（最新）；DR10（常用稳定版）', drDate:'DR11: 2026-08',
 area:'DR11 ≈ 3/4 全天（≈3 万 deg²）⚠；DR10 >20,000 deg²', areaN:30000,
 bands:'g r i z（DR10 起含 i）+ WISE W1–W4 强制测光',
 depth:'DR10 预测 5σ（2 次曝光）≈ g 24.7 / r 23.9 / z 23.0', depthN:23.9,
 resAng:'≈1″/像素；DECam 0.26″', nsrc:'DR10 ≈ 28.3 亿 primary 源；DR11 ≈ 40 亿 ⚠', nN:9.6,
 sci:'DESI 选源底图；南天最深的公共测光 + Tractor 形态拟合目录；现已成“默认匹配底图”。',
 links:[['官网 legacysurvey.org','https://www.legacysurvey.org/'],['DR10 说明','https://www.legacysurvey.org/dr10/description/'],['Sky Viewer','https://www.legacysurvey.org/viewer'],['Data Lab (LS DR10)','https://datalab.noirlab.edu/']],
 paper:['巡天总览（Dey et al. 2019）','https://arxiv.org/abs/1804.08657'],
 note:'Tractor 目录直接给出 PSF/REX/EXP/DEV/Ser 形态类型与 nanomaggy 流量；W1–W4 来自 unWISE 叠加。DR11 号称史上最大 2D 天图（5.6 万亿像素）。'},

{id:'hsc', name:'HSC-SSP', en:'Hyper Suprime-Cam Subaru Strategic Program', reg:['img'],
 d:{p:'grizy 五带图像 + 双管线星表(Wide/Deep/UDes)', a:'SMOKA、hsc-release.mtk.nao.ac.jp 查询/切图', c:'Wide 单带~多次；Deep 层数十次访问', v:'PDR3 星表数亿源 ⚠'},
 status:'run', facility:'Subaru 8.2 m + HSC（1.77 deg² 视场）', dr:'PDR3（最终版 PDR4 日期未定 TBD）', drDate:'2021-12',
 area:'Wide 设计 1,400 / 已观测 ≈2,200 deg²（满深度 ≈670）+ Deep/UltraDeep', areaN:2200,
 bands:'g r i z y（+Deep 层窄带）',
 depth:'Wide 满深度 5σ（2″ 孔径）≈ 27.0 / 26.6 / 26.4 / 25.5 / 24.7', depthN:26.6,
 resAng:'0.168″/像素；≈0.6–0.8″', nsrc:'≈10 亿级测光源 ⚠', nN:9,
 sci:'地面最深的大视场成像：弱透镜宇宙学、高红移星系/LBG、强透镜、星系团。',
 links:[['PDR3 数据文档','https://hsc-release.mtk.nao.ac.jp/doc/'],['SSP 官网','https://hsc.mtk.nao.ac.jp/ssp/'],['发布计划','https://hsc.mtk.nao.ac.jp/ssp/data-release/']],
 paper:['PDR3（Aihara et al. 2022, PASJ 74, 247）','https://arxiv.org/abs/2108.13045'],
 note:'深度≈DES+2 mag、面积≈DES 的 1/2.5。最终版 PDR4（含 S23A 学期数据）反复延期，官方明确“尚无日期”。弱透镜剪切目录需申请。'},

{id:'kids', name:'KiDS', en:'Kilo-Degree Survey (+VIKING 近红外)', reg:['img','ir'],
 d:{p:'ugri(+VIKING) 图像 + 星表 + 透镜剪切表', a:'KiDS 官网、ESO 档案、VizieR II/383', c:'每带数次浅叠', v:'DR5 ≈1 亿源十波段'},
 status:'done', facility:'VST 2.6 m OmegaCAM + VISTA 4.1 m（VIKING）', dr:'DR5（最终版）', drDate:'2024–2025（ESO Phase 3: 2025-03）',
 area:'1,347 deg²（南天两条带）', areaN:1347,
 bands:'u g r i + Z Y J H Ks（9 波段）',
 depth:'5σ ≈ u 24.2 / g 25.1 / r 24.9 / i 23.8；近红外 ≈ 19–21 ⚠', depthN:24.9,
 resAng:'0.21″/像素（OmegaCAM）', nsrc:'≈1 亿源', nN:8,
 sci:'9 波段测光 + 弱透镜；与 GAMA/VIKING 深度搭配的南天中等深度标杆。',
 links:[['KiDS 官网','https://kids.strw.leidenuniv.nl/'],['ESO 档案（Phase 3）','https://archive.eso.org/'],['DR5 论文 (2503.19439)','https://arxiv.org/abs/2503.19439']],
 paper:['KiDS-DR5（Wright et al. 2024, A&A）','https://arxiv.org/abs/2503.19439'],
 note:'巡天已完成、DR5 为最终版。提供 THELI 处理的 coadd 与 9 波段源表；透镜分析用的 value-added 目录随论文发布。'},

{id:'skymapper', name:'SkyMapper', en:'SkyMapper Southern Sky Survey', reg:['img','gspec'],
 d:{p:'uvgriz 南天图像 + 星表 + 变星/SO 表', a:'SkyMapper 门户(查询/图像/cutout)', c:'每带多次访问', v:'DR4 >150 亿检测行'},
 status:'run', facility:'SkyMapper 1.35 m（澳洲 Siding Spring）', dr:'DR4（DR5 已在官网陆续出现数据表）', drDate:'2024-02',
 area:'南天全半球 + Dec<+16°（≈20,900 deg²）', areaN:20900,
 bands:'u v g r i z（uv/u 为金属丰度敏感能段）',
 depth:'堆叠 5σ ≈ 20–21.5（视波段）⚠', depthN:21.2,
 resAng:'≈1″ FWHM（堆叠）', nsrc:'>150 亿检测（DR4，含历元）', nN:10.2,
 sci:'南天 ugriz+uv 底图；贫金属恒星搜寻、南天暂现源、银河系晕结构。',
 links:[['官网（数据申请）','https://skymapper.anu.edu.au/'],['DR4 论文 (2402.02015)','https://arxiv.org/abs/2402.02015'],['NOIRLab Data Lab','https://datalab.noirlab.edu/']],
 paper:['DR4（Onken et al. 2024, PASA）','https://arxiv.org/abs/2402.02015'],
 note:'独特卖点是 uv/u 波段（可做 [Fe/H] 直接估算）。测光对点源优化，扩展源测光慎用（官方声明不保证）。'},

{id:'delve', name:'DELVE', en:'DECam Local Volume Exploration Survey', reg:['img'],
 d:{p:'griz 叠加图像 + 测光星表 + 卫星星系列表', a:'NOIRLab Data Lab(表查询/切图)', c:'汇总一切 DECam 档案多次叠深(All Data Everywhere)', v:'DR2 ≈25 亿 / DR3 ≈26 亿检测'},
 status:'run', facility:'Blanco 4 m + DECam（3 deg² 视场）', dr:'DR3（2025，含 DES Y6，"All Data Everywhere"）；DR2（2022 论文）', drDate:'DR3: 2025',
 area:'DR2 >21,000 deg²（|b|>10°）；DR3 汇总全部 DECam 档案（≈39,000 次曝光）', areaN:21000,
 bands:'g r i z（4 宽带）',
 depth:'典型 5σ ≈ g 24 / r 24 / i 23.5（DR2 口径）', depthN:24.0,
 resAng:'0.263″/像素', nsrc:'DR2 ≈ 25 亿 / DR3 ≈ 26 亿检测', nN:9.4,
 sci:'近邻宇宙最深广域成像：超暗矮星系卫星、银河系外晕亚结构、近邻星系恒星分辨。',
 links:[['官网','https://delve-survey.github.io/'],['数据（NOIRLab Data Lab）','https://datalab.noirlab.edu/data/delve']],
 paper:['DR2 论文（2022, ApJS）','https://arxiv.org/abs/2203.16565'],
 note:'DR3 整合社区+DES Y6 数据，2025 年从中新发现多个超暗卫星星系；选源做恒星/星系分类用 star/galaxy 分数。'},

{id:'jplus', name:'J-PLUS', en:'Javalambre Photometric Local Universe Survey', reg:['img'],
 d:{p:'12 带图像 + 双孔径测光星表', a:'CEFCA 档案(web 查询/API)', c:'每带单次短曝光', v:'DR3 数千万源'},
 status:'run', facility:'OAJ T80 0.83 m + T80Cam（2 deg² 视场）', dr:'DR3（2022-07）；观测持续', drDate:'DR3: 2022-07',
 area:'≈3,192 deg²（掩膜后 2,881）', areaN:3192,
 bands:'12 波段：5 宽带 + 7 窄带（Hα、Ca 三重线等）',
 depth:'宽带 5σ ≈ 21–21.5 ⚠', depthN:21.3,
 resAng:'0.55″/像素', nsrc:'数千万级检测（未统一汇总口径）', nN:0,
 sci:'窄带测光化学：恒星金属丰度/[α/Fe]、Hα 发射线星系、近邻星系种群与银河系映射。',
 links:[['官网','https://www.j-plus.es/'],['DR3 数据（CEFCA 档案）','https://archive.cefca.es/catalogues/jplus-dr3']],
 paper:['DR3 发布页（官方）','https://www.j-plus.es/datareleases/data_release_dr3'],
 note:'12 波段测光定标达 1% 精度（2024, A&A 683）；与 S-PLUS 构成南北对应体系。'},

{id:'splus', name:'S-PLUS', en:'Southern Photometric Local Universe Survey', reg:['img'],
 d:{p:'12 带图像 + 测光星表(DR4 共 1,629 场)', a:'splus.cloud、CDS、Data Lab', c:'每带单次短曝光', v:'DR4 数千万源'},
 status:'run', facility:'Cerro Pachón T80-S 0.8 m + T80S-S', dr:'DR4（2024-09 论文）', drDate:'DR4: 2024',
 area:'≈3,000 deg²（目标 9,300）', areaN:3000,
 bands:'12 波段：5 宽带 + 7 窄带（同 J-PLUS 体系）',
 depth:'宽带 5σ ≈ 21 ⚠', depthN:21.0,
 resAng:'0.55″/像素', nsrc:'DR4 12 波段测光（1,629 场）', nN:0,
 sci:'南天 12 波段：变星、银河系晕、近邻星系恒星种群；photo-z 精度 r<20 达 σ≈0.02。',
 links:[['官网','https://splus.cloud/'],['Data Lab 镜像','https://datalab.noirlab.edu/data/splus']],
 paper:['DR4 论文（2024, A&A）','https://www.aanda.org/articles/aa/abs/2024/09/aa49725-24/aa49725-24.html'],
 note:'DR4 初期限合作组，后经 CDS（II/380）与 Data Lab 公开；J-PAS 体系的南天版。'},

{id:'jpas', name:'J-PAS', en:'Javalambre Physics of the Accelerating Universe Survey', reg:['img'],
 d:{p:'56 带图像 + 超多参数星表(EDR 每源 1,000+ 参数)', a:'CEFCA/IAA 档案', c:'每窄带多次短曝光', v:'EDR 6 万+ 源；全巡天预期数亿'},
 status:'run', facility:'OAJ T250 2.55 m + JPCam（5 deg² 视场，14 CCD）', dr:'EDR（2024-11，12 deg² 全 56 波段）；宽场巡天已启动', drDate:'EDR: 2024-11',
 area:'EDR 12 deg²；设计 ≈8,000 deg²（1/5 天区）', areaN:8000,
 bands:'56 波段：54 窄带（≈14 nm）+ 2 中带',
 depth:'中带 5σ ≈ 22；窄带 ≈ 21–21.5 ⚠', depthN:21.5,
 resAng:'0.23″/像素', nsrc:'EDR 6 万+ 源（每源 1,000+ 参数）；全巡天预期数亿', nN:0,
 sci:'"全景光谱仪"式窄带测光：photo-z 精度堪比低分辨光谱，三维恒星金属丰度测绘。',
 links:[['官网','https://www.j-pas.org/'],['数据发布页','https://www.j-pas.org/datareleases']],
 paper:['EDR 发布说明（IAA 档案）','https://archive.iaa.csic.es/en/news/j-pas-astronomical-project-releases-first-data-its-mapping-universe'],
 note:'前身 miniJPAS 已验证体系；宽场观测 2025 年起爬坡，DR1 时间表待官方公布。'},

{id:'rubin', name:'Rubin / LSST', en:'Vera C. Rubin Observatory · LSST', reg:['img','time'],
 d:{p:'警报流(<60 s) + 单次差分图像 + DIASource/Object 表', a:'RSP 门户 + 警报 broker(ALeRCE/Fink/ANTARES)', c:'单次 30 s ×2 快照；设计每 3–4 天全天重访', v:'设计每夜 ≈20 TB、10 年 ≈60 PB ⚠'},
 status:'next', facility:'8.4 m（有效 6.7 m）Simonyi 望远镜 + LSSTCam（32 亿像素，9.6 deg²）', dr:'DP2 已发布（2026-06-27）；DR1 ≈ 2027', drDate:'DP2: 2026-06',
 area:'设计 18,000 deg²；DP1 ≈ 7 个 ComCam 视场（~40 deg²）', areaN:18000,
 bands:'u g r i z y',
 depth:'单次 5σ r≈24.5；10 年堆叠 r≈27.5（设计）', depthN:27.5,
 resAng:'0.2″/像素；≈0.7″（中位视宁度）', nsrc:'预计 ≈200 亿源；警报 ~1,000 万/夜', nN:10.3,
 sci:'十年时域电影 + 最深最广的 ugrizy 堆叠：暂现源、弱透镜、太阳系、银河系时域。',
 links:[['Rubin 官网','https://rubinobservatory.org/'],['DP1 文档','https://dp1.lsst.io/'],['DP2 文档','https://dp2.lsst.io/'],['数据权益说明','https://rubinobservatory.org/for-scientists/data-products']],
 paper:['LSST 科学书（Ivezić et al. 2019）','https://arxiv.org/abs/0805.2366'],
 note:'2025-06 First Look；2026-02-24 正式巡天启动。DR1 之前原始数据限于合作组与数据权益国；DP1/DP2 文档与部分产品已公开，警报流经 ALeRCE/Fink 等 broker 公开。'},

/* ---------------- 红外 / 紫外 ---------------- */
{id:'twomass', name:'2MASS', en:'Two Micron All Sky Survey', reg:['ir'],
 d:{p:'JHKs 全天图像 + 点源/扩展源表', a:'IRSA(Gator 批量查询)', c:'单次曝光叠加', v:'点源 ≈4.7 亿 + 扩展源 165 万'},
 status:'done', facility:'2×1.3 m（美国 AZ + 智利）', dr:'终版（All-Sky Data Release）', drDate:'2003',
 area:'全天 41,253 deg²', areaN:41253,
 bands:'J H Ks（Vega 系统！）',
 depth:'10σ 完整性 J 15.8 / H 15.1 / Ks 14.3（Vega）', depthN:16.9,
 resAng:'2–2.5″ FWHM', nsrc:'PSC ≈ 4.7 亿点源 + 165 万扩展源', nN:8.67,
 sci:'全天近红外基准框架：恒星计数、银河系结构、星系交叉匹配的“硬通货”。',
 links:[['IRSA 2MASS','https://irsa.ipac.caltech.edu/Missions/2mass.html'],['点源目录检索','https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-scan?mission=irsa&submit=Select&shortcmd=2MASS_PSC']],
 paper:['2MASS（Skrutskie et al. 2006, AJ）','https://ui.adsabs.harvard.edu/abs/2006AJ....131.1163S/abstract'],
 note:'注意是 Vega 星等。与 WISE 组成全天红外标配；更深的近红外看 UHS/VHS/VIKING。'},

{id:'wise', name:'WISE / AllWISE / unWISE / CatWISE', en:'Wide-field Infrared Survey Explorer', reg:['ir','time'],
 d:{p:'四带全天图像 + 星表 + NEOWISE 时域 + unWISE 年叠', a:'IRSA(unWISE/CatWISE/光变全在)', c:'原始单次；unWISE 每 6 个月一叠', v:'AllWISE ≈7.5 亿源 ⚠'},
 status:'done', facility:'WISE 0.4 m 空间望远镜（2009 发射；NEOWASE 延寿至 2024-08）', dr:'AllWISE（2013）+ CatWISE2020 + unWISE 叠加', drDate:'2020–2023（滚动）',
 area:'全天', areaN:41253,
 bands:'W1 W2 W3 W4（3.4 / 4.6 / 12 / 22 μm，Vega）',
 depth:'AllWISE 5σ ≈ W1 16.9 / W2 15.7 / W3 11.5 / W4 8.0 ⚠；unWISE 多年叠加再深 ~0.5–1 mag', depthN:17.7,
 resAng:'W1/W2 ≈ 6″（HR）；12″–24″（长波）', nsrc:'AllWISE ≈ 7.47 亿源；CatWISE2020 >10 亿 ⚠', nN:9,
 sci:'中红外全天：AGN 筛选（W1–W2 色）、YSO/尘埃、褐矮星；NEOWISE 12 年时域光变。',
 links:[['IRSA WISE','https://irsa.ipac.caltech.edu/Missions/wise.html'],['unWISE 叠加','https://unwise.me/'],['CatWISE（IRSA）','https://irsa.ipac.caltech.edu/workshops/CatWISE2020/']],
 paper:['AllWISE（Cutri et al. 2021/2013, Explanatory Supplement）','https://wise2.ipac.caltech.edu/docs/release/allwise/'],
 note:'unWISE/neowiser 叠加图配强制测光是现在做 NIR/MIR 匹配的首选（Legacy Surveys 已内置 W1/W2）。'},

{id:'vhs', name:'VHS', en:'VISTA Hemisphere Survey', reg:['ir'],
 d:{p:'YJHKs 图像 + 星表', a:'ESO Phase 3 档案、VSA', c:'每带 1–2 次浅叠', v:'≈10 亿检测 ⚠'},
 status:'run', facility:'VISTA 4.1 m + VIRCAM（智利 Paranal）', dr:'滚动发布（DR6+，经 ESO 档案）⚠', drDate:'—',
 area:'南天 ≈17,000 deg²（VHS-DES 区更深）', areaN:17000,
 bands:'Y J H Ks（南部部分区域仅 Ks+J）',
 depth:'5σ ≈ J 20.6 / H 20.4 / Ks 19.9 ⚠（AB）', depthN:21.1,
 resAng:'0.34″/像素；≈0.9–1.1″', nsrc:'数亿源', nN:8.7,
 sci:'南天近红外底图，与 DES/KiDS/SkyMapper 配套；QSO、褐矮星、银河系结构。',
 links:[['ESO Phase 3 / 档案','https://archive.eso.org/wdb/wdb/eso/eso_archive_main/form'],['VHS（ESO 巡天页）','https://www.eso.org/sci/observing/PublicSurveys/scienceSurveys.html']],
 paper:['VHS DR5（McMahon et al. 2021）','https://ui.adsabs.harvard.edu/abs/2021MNRAS.506.5218M/abstract'],
 note:'数据经 ESO Science Archive 滚动开放，无传统“DR 数字”节奏；配合 VHS-DES 深区 (~J≈21.5) 使用。'},

{id:'uhs', name:'UHS', en:'UKIDSS Hemisphere Survey', reg:['ir'],
 d:{p:'JHK 图像 + 星表(UKIDSS LAS 加深南扩)', a:'WSA(SQL 查询)', c:'单次', v:'≈ 数亿源 ⚠'},
 status:'run', facility:'UKIRT 3.8 m + WFCAM（夏威夷）', dr:'DR1', drDate:'2023',
 area:'北天 ≈4,700 deg²（Dec > −3°）⚠', areaN:4700,
 bands:'J H K（部分 Y）',
 depth:'5σ ≈ J 20.3 / H 19.6 / K 18.4 ⚠（AB）', depthN:20.8,
 resAng:'0.4″/像素；≈0.7–0.9″', nsrc:'>3 亿源 ⚠', nN:8.5,
 sci:'UKIDSS LAS 的 3 倍深度升级：冷恒星/褐矮星、高红移 QSO、北天近红外底图。',
 links:[['WFCAM 科学档案（CASU）','https://casu.cam.ac.uk/'],['UHS DR1 论文页','https://ui.adsabs.harvard.edu/abs/2023MNRAS.522.5357D/abstract']],
 paper:['UHS DR1（Dye et al. 2023? MNRAS）⚠','https://ui.adsabs.harvard.edu/abs/2023MNRAS.522.5357D/abstract'],
 note:'与 PS1/Legacy 北天光学叠加使用效果最佳；成图质量好于老 UKIDSS LAS。'},

{id:'viking', name:'VIKING', en:'VISTA Kilo-degree Infrared Galaxy survey', reg:['ir'],
 d:{p:'ZYJHKs 图像 + 星表(最方便经 KiDS DR5 十波段表)', a:'ESO 档案、KiDS DR5 页面', c:'每带多次浅叠', v:'合并十波段表 ≈1 亿源'},
 status:'done', facility:'VISTA 4.1 m + VIRCAM', dr:'DR4（2020-03，Phase 3）；DR5 已悄然入档 ⚠', drDate:'DR4: 2020-03',
 area:'≈1,500 deg²（KiDS 天区）', areaN:1500,
 bands:'Z Y J H Ks（5 近红外）',
 depth:'5σ ≈ Z 23.1 / Y 22.3 / JHKs ≈ 21.2 ⚠（AB）', depthN:21.2,
 resAng:'0.34″/像素', nsrc:'并入 KiDS DR5 十波段星表（≈1 亿源）', nN:0,
 sci:'KiDS 光学天区的近红外补全：恒星质量、静息波段测光、高红移类星体筛选。',
 links:[['ESO Phase 3','https://eso.org/rm/publicAccess'],['KiDS DR5（含 VIKING）','https://kids.strw.leidenuniv.nl/DR5/']],
 paper:['VIKING 概览（Edge et al. 2013）','https://ui.adsabs.harvard.edu/abs/2013Msngr.154...32E/abstract'],
 note:'单独取数走 ESO 档案；最方便入口是 KiDS DR5 的 ugri+ZYJHKs 十波段星表。'},

{id:'vvv', name:'VVV / VVVX', en:'VISTA Variables in the Vía Láctea (eXtended)', reg:['ir','time'],
 d:{p:'ZYJHKs 多历元图像 + 红化图 + 变星/星团表', a:'ESO 档案、VSA、CDS(II/376 等)', c:'Ks 多历元(数十~百余次)，其余单次', v:'≈5 亿检测'},
 status:'done', facility:'VISTA 4.1 m + VIRCAM（多历元）', dr:'最终全量 2025-12（ESO Phase 3）；科学星表 DR5 / DR4.2（CDS）', drDate:'2025-12',
 area:'≈1,700 deg²（核球 + 南银盘）', areaN:1700,
 bands:'Z Y J H Ks + 窄带 H₂',
 depth:'单历元 5σ Ks ≈ 18（Vega）⚠；叠加更深', depthN:18.0,
 resAng:'0.34″/像素', nsrc:'≈5 亿检测（数十至百余次历元）', nN:8.7,
 sci:'银河系核球/盘最深红外时域：红化地图、变星（RR Lyrae/造变）距离、星团普查。',
 links:[['官网','https://vvvsurvey.org/'],['数据发布页','https://vvvsurvey.org/data-releases/']],
 paper:['VVVX 概览（2024）','https://arxiv.org/abs/2406.16646'],
 note:'2024-10 完成全部观测（13 年 ≈420 夜），"迄今最大的银河系红外图"。'},

{id:'ukidss', name:'UKIDSS', en:'UKIRT Infrared Deep Sky Survey', reg:['ir'],
 d:{p:'LAS/GPS/GCS/DXS/UDS 图像 + 星表', a:'WSA(SQL 查询，免费)', c:'LAS 每带 1–4 次 ⚠', v:'≈ 数亿源'},
 status:'done', facility:'UKIRT 3.8 m + WFCAM', dr:'WSA 存档 DR11.x（UDS DR11 为终版）', drDate:'DR11: 2020 年代 ⚠',
 area:'五子巡天合计 ≈7,500 deg²（LAS 4,000 为主体）', areaN:7500,
 bands:'Y J H K（+窄带）；LAS/GPS/GCS/DXS/UDS 五部分',
 depth:'LAS 5σ K ≈ 18.2（Vega，≈20.0 AB）；UDS K ≈ 25（AB，最深）', depthN:20.0,
 resAng:'0.4″/像素', nsrc:'LAS ≈ 数亿检测 ⚠', nN:0,
 sci:'北天近红外奠基巡天：冷恒星/褐矮星、类星体、UDS 深场星系演化。',
 links:[['官网','http://www.ukidss.org/'],['WSA 科学档案','http://wsa.roe.ac.uk/']],
 paper:['UKIDSS 概览（Lawrence et al. 2007）','https://ui.adsabs.harvard.edu/abs/2007MNRAS.379.1599L/abstract'],
 note:'UHS（本表另列）是其 LAS 的加深南扩；数据经 WSA 免费获取。'},

{id:'ultravista', name:'UltraVISTA', en:'Ultra-deep VISTA survey of COSMOS', reg:['ir'],
 d:{p:'YJHKs(+窄带) 深/超深两层图像 + COSMOS2025 星表', a:'ESO 档案、IRSA', c:'2010–2025 逐季累积叠深', v:'超深层每像素数百次访问'},
 status:'done', facility:'VISTA 4.1 m + VIRCAM', dr:'DR6 "Legacy"（2025-11，最终版，无 DR7）', drDate:'2025-11',
 area:'≈1.8 deg²（COSMOS 1.5°×1.2°）', areaN:1.8,
 bands:'Y J H Ks + 2 窄带（深/超深两层）',
 depth:'超深层 5σ Ks ≈ 25.3 ⚠；DR6 全区深度均匀', depthN:25.3,
 resAng:'0.34″/像素', nsrc:'配套 COSMOS2025 星表（40+ 波段测光）', nN:0,
 sci:'COSMOS 场最深近红外大视场：z~3–7 星系、静息星系、超大质量黑洞宿主。',
 links:[['官网','https://ultravista.org/'],['IRSA 数据','https://irsa.ipac.caltech.edu/data/COSMOS/']],
 paper:['ESO DR6 发布说明','https://www.eso.org/sci/publications/announcements/sciann17649.html'],
 note:'与 DEVILS、COSMOS-Web、HSC 同场无缝叠加，多波段 SED 最完整的深场。'},

{id:'cosmosweb', name:'COSMOS-Web', en:'COSMOS-Web（JWST Cycle 1 大项目）', reg:['ir'],
 d:{p:'NIRCam 四带镶嵌图 + 测光星表(+MIRI 区)', a:'COSMOS 数据中心(Caltech/IAP)、MAST', c:'2023-12–2025 多轮累积', v:'0.54 deg² 全量公开'},
 status:'done', facility:'JWST + NIRCam（另 ≈0.2 deg² MIRI）', dr:'DR1 全量公开（NIRCam+MIRI 镶嵌图 + 测光星表）', drDate:'2025',
 area:'0.54 deg²（约三个满月）', areaN:0.54,
 bands:'F115W / F150W / F277W / F444W（+MIRI）',
 depth:'5σ ≈ 27.5–28.2（AB）', depthN:27.8,
 resAng:'0.03–0.06″/像素', nsrc:'数十万星系（含 z>10 候选）', nN:0,
 sci:'迄今最大连续 JWST 近红外成像：z~6–12 星系、尘埃遮挡质量、强透镜（COWLS）。',
 links:[['官方 DR 页（Caltech）','https://cosmos.astro.caltech.edu/page/cosmosweb'],['DR1 数据（IAP）','https://cosmos2025.iap.fr/']],
 paper:['COSMOS-Web 星表论文（2025, A&A）','https://www.aanda.org/articles/aa/abs/2025/12/aa55799-25/aa55799-25.html'],
 note:'255 小时 JWST 项目；与 UltraVISTA/COSMOS2025 多波段体系直接对接。'},

{id:'neowise', name:'NEOWISE', en:'NEOWISE Reactivation（WISE 时域）', reg:['ir','time'],
 d:{p:'每 6 个月全天 W1/W2 单曝表 + 全天时域光变', a:'IRSA(单曝源表/unWISE 年叠/CatWISE)', c:'每 6 个月全天一遍，共 ≈21 遍', v:'数亿源 × 21 历元'},
 status:'done', facility:'WISE 0.4 m 空间望远镜（近地天体模式）', dr:'最终释放 2024-11-14（10.6 年全量）', drDate:'2024-11',
 area:'全天 ×≈21.3 遍（每 6 个月一遍）', areaN:41253,
 bands:'W1 3.4 / W2 4.6 μm',
 depth:'单历元 5σ W1 ≈ 17.5 ⚠', depthN:17.5,
 resAng:'W1 波束 ≈6″（像素 2.75″）', nsrc:'全天数亿源 W1/W2 光变；163 万次太阳系天体检测', nN:0,
 sci:'最长基准的中红外时域：尘埃遮蔽 AGN、变星、褐矮星；小行星热物理。',
 links:[['最终释放（IPAC）','https://wise2.ipac.caltech.edu/docs/release/neowise'],['IRSA','https://irsa.ipac.caltech.edu/']],
 paper:['任务总结（JPL）','https://www.jpl.nasa.gov/missions/neowise'],
 note:'2024-08 停运、2025 年再入大气层；时域分析可用 unWISE 年度叠加与 CatWISE。'},

{id:'galex', name:'GALEX', en:'Galaxy Evolution Explorer', reg:['uv'],
 d:{p:'FUV/NUV 图像 + 星表 + 时域(gPhoton)', a:'MAST(gPhoton 光变/切图)、VizieR', c:'AIS 单次；DIS 深场多次', v:'GR7 ≈ 数亿 UV 源 ⚠'},
 status:'done', facility:'GALEX 0.5 m 空间紫外望远镜（2003–2013）', dr:'终版目录（GUVCat 等）', drDate:'2017（GUVCat）',
 area:'全天（AIS 浅层）；DIS/CAUSE 深场更深', areaN:41253,
 bands:'FUV（154 nm）/ NUV（230 nm），AB',
 depth:'AIS 5σ ≈ FUV 19.9 / NUV 20.8；深场至 ≈24–25', depthN:20.8,
 resAng:'≈4–5″ FWHM', nsrc:'≈7 千万紫外源 ⚠（GUVCat AIS）', nN:7.85,
 sci:'全天紫外：恒星形成率、QSO/SED 匹配、热星与白矮星。',
 links:[['MAST GALEX','https://galex.stsci.edu/'],['GUVCat（MAST）','https://galex.stsci.edu/gr6/']],
 paper:['GALEX（Martin et al. 2005, ApJL）','https://ui.adsabs.harvard.edu/abs/2005ApJ...619L...1M/abstract'],
 note:'仍是最全面的全天紫外资源；2013 年停止观测，部分天区（内盘）因安全未观测。'},

/* ---------------- 空间任务 ---------------- */
{id:'gaia', name:'Gaia', en:'ESA Gaia（天测 + 测光 + 中低分辨光谱）', reg:['astro','gspec','img'],
 d:{p:'位置/自行/视差 + G/BP/RP 测光 + 视向速度 + 低分辨光谱', a:'Gaia Archive(ADQL/TAP) + 多镜像', c:'DR3 为 34 个月平均；DR4 将发历元数据', v:'DR3 ≈18 亿源'},
 status:'run', facility:'ESA 天测卫星（1.45 m×0.5 m，L2）', dr:'DR3（最新）；DR4 预计 2026-12', drDate:'DR3: 2022-06-13',
 area:'全天', areaN:41253,
 bands:'G（330–1,050 nm）+ BP/RP 低分辨 + RVS',
 depth:'G ≈ 20.7（5σ 完整性）', depthN:20.7,
 resAng:'天测精度 ≈0.4 mas（G=20）→ 0.02 mas（G=15）；视差/自行同量级', nsrc:'18.12 亿源；RVS 平均光谱 ≈3,300 万（R≈11,500）；BP/RP ≈2 亿', nN:9.26,
 sci:'银河系结构与运动学参考系、双星/变星、系外行星、QSO 参考架——几乎所有巡天的天测基准。',
 links:[['Gaia 官网','https://www.cosmos.esa.int/gaia'],['数据档案','https://gea.esac.esa.int/archive/'],['DR4 专页','https://www.cosmos.esa.int/web/gaia/dr4']],
 paper:['DR3 总览（Gaia Collaboration 2023, A&A 674, A1）','https://arxiv.org/abs/2208.00211'],
 note:'2025-01 结束观测。DR4（66 个月数据）将首次发布历元天测/历元测光、RVS 历元光谱等 130+ 数据产品——双星/系外行星/暂现源研究的游戏规则改变者，预计 2026 年 12 月。'},

{id:'euclid', name:'Euclid', en:'ESA Euclid（空间光学+NIR 成像/无缝光谱）', reg:['img','ir','xspec'],
 d:{p:'VIS/NISP 图像 + 形状/测光星表 + 强透镜候选表', a:'Euclid 科学档案(ESA EAS)、Caltech Q 页', c:'宽场巡天 6 年计划，逐季释放', v:'Q1 = 63 deg² 预览；DR1-Foundation 首半年'},
 status:'next', facility:'Euclid 1.2 m（L2）；VIS 6 亿像素 + NISP', dr:'Q1（2025-03）；Q2（2026-06）；DR1-Foundation 2026-11-12', drDate:'Q2: 2026-06-24',
 area:'宽场设计 14,000 deg²；Q1 = 63.1 deg² 深场预览', areaN:14000,
 bands:'IE（550–900 nm，VIS）+ YE/HE/JE（NIR）；无缝光谱 R≈250',
 depth:'宽场 IE ≈ 24.5（10σ 点源）；深场 26+ ⚠', depthN:24.5,
 resAng:'VIS 0.1″/像素（衍射限 ~0.17″）；NIR ≈0.3″', nsrc:'Q1 ≈ 2,600 万源；DR1 预计 10 亿+（宽场）', nN:9,
 sci:'空间弱透镜 + NIR 重子声学振荡；高分辨近红外成像（哈勃级像质、百倍面积）。',
 links:[['ESA Euclid','https://www.cosmos.esa.int/web/euclid'],['Euclid 联盟','https://www.euclid-ec.org/'],['IRSA（美国节点）','https://irsa.ipac.caltech.edu/Missions/euclid.html'],['发布时间线（Caltech）','https://euclid.caltech.edu/']],
 paper:['Euclid 巡天科学定义（Laureijs et al. 2011）','https://arxiv.org/abs/1110.3193'],
 note:'DR1 拆成两步：2026-11-12 "DR1 Foundation"（首半年宽场数据）、2027 年中完整 DR1。Q2 为银核微透镜/系外行星深场。'},

{id:'spherex', name:'SPHEREx', en:'NASA Spectro-Photometer for the History of the Universe', reg:['ir','xspec'],
 d:{p:'0.75–5 μm 全天 100+ 通道光谱光度 + 源表', a:'IRSA(随 Quick Release 滚动)', c:'全天 4 次/日，极区更深 ⚠', v:'预期数亿源低分辨光谱'},
 status:'run', facility:'SPHEREx 0.2 m 空间光谱光度计（2025-03-11 发射）', dr:'Quick Release 滚动（QR2 2026-04；下一个 QR 2026-09）', drDate:'2026-04',
 area:'全天（102 个红外“颜色”通道）', areaN:41253,
 bands:'0.75–5 μm，102 通道；R≈41（短波）/ R≈135（长波）',
 depth:'每通道 5σ ≈ 19–20 AB ⚠', depthN:19.5,
 resAng:'≈2.2″–6.4″（视通道）', nsrc:'目标 >4.5 亿星系 + 1 亿恒星的光谱', nN:8.7,
 sci:'全天低分辨光谱普查：冰与尘埃、河外背景光、z>10 大尺度结构。',
 links:[['IRSA SPHEREx','https://irsa.ipac.caltech.edu/data/SPHEREx/'],['任务官网','https://www.spherex.caltech.edu/'],['JPL SPHEREx','https://www.jpl.nasa.gov/missions/spherex/']],
 paper:['SPHEREx 任务论文（Doré et al.）','https://arxiv.org/abs/1805.05489'],
 note:'2025-07 起在 IRSA 每周滚动发布谱图像数据；“每个源都有光谱”是其与测光巡天的本质区别。'},

{id:'roman', name:'Roman', en:'Nancy Grace Roman Space Telescope', reg:['ir','time','xspec'],
 d:{p:'WFI 近红外图像 + 无缝光谱 + 微透镜时域', a:'MAST/IPAC(2027 首光后滚动开放)', c:'核心+社区巡天分层，5 年任务', v:'视场 0.28 deg²；HLSS 规划 ≈2,000 deg²'},
 status:'next', facility:'Roman 2.4 m（宽视场 WFI 3 亿像素，0.28 deg²）', dr:'2026-09 已发射；首光图 ≈2027-01', drDate:'2026-09（发射）',
 area:'高纬度宽场巡天 HLSS 设计 ≈2,000 deg²', areaN:2000,
 bands:'0.48–2.3 μm（F062–F213）+ prism/grism 无缝光谱（R≈75–650）',
 depth:'HLSS 5σ ≈ 27 AB（近红外）⚠', depthN:27,
 resAng:'≈0.11″/像素；近 HST 像质', nsrc:'—', nN:0,
 sci:'近红外深场（Euclid/Rubin 的加深版）+ 银核微透镜系外行星统计。',
 links:[['Roman 官网','https://roman.nasa.gov/'],['Roman 文档（STScI）','https://roman-docs.stsci.edu/']],
 paper:['Roman 巡天定义（Spergel et al. 2015）','https://arxiv.org/abs/1503.03757'],
 note:'2026 年 9 月发射（早于“不晚于 2027-05”的合同约束）；2027 年起观测。⚠ 时间线以 NASA 官方为准。'},

{id:'csst', name:'CSST / 空间站望远镜', en:'Chinese Space Station Telescope（Xuntian）', reg:['img','xspec'],
 d:{p:'多色成像 + 无缝光谱 + 太空暂现监测', a:'国家天文科学数据中心(CNADC)', c:'在轨 5 年计划 ⚠', v:'设计 17,500 deg²'},
 status:'next', facility:'2 m 主镜，与天宫共轨飞行（长征五号 B，海南发射）', dr:'计划 2027 年发射', drDate:'计划 2027',
 area:'设计 17,500 deg²', areaN:17500,
 bands:'18 波段测光（NUV–NIR，255–1,000 nm）+ 多通道成像仪 MCI + 无缝光谱（R≈200）',
 depth:'多波段 5σ ≈ 24–26（视波段，设计）⚠', depthN:25,
 resAng:'≈0.15″（像素尺度设计）', nsrc:'—', nN:0,
 sci:'大天区多色测光 + 无缝光谱；暗物质/暗能量、星系演化、ML 分类样本。',
 links:[['Xuntian 概览（概况）','https://en.wikipedia.org/wiki/Xuntian'],['CSST 科学背景（arXiv）','https://arxiv.org/abs/2306.11129']],
 paper:['CSST 综述（Zhan 2021）','https://ui.adsabs.harvard.edu/abs/2021SCPMA..6449501Z/abstract'],
 note:'发射日期已多次推迟（原 ~2023 → 现计划 2027）；数据政策与国际合作细节建议持续关注国家天文台发布。'},

/* ---------------- 光谱 · 河外 ---------------- */
{id:'desi', name:'DESI', en:'Dark Energy Spectroscopic Instrument', reg:['xspec'],
 spec:'R≈2,000（BOSS）；BGS 更低分辨', rN:2000,
 d:{p:'四类目标光谱(BGS/LRG/ELG/QSO) + 红移表 + coadd 光谱', a:'DESI 数据门户(目录/光谱直接下载)', c:'每板 1–4 次曝光(15–30 分钟级)', v:'DR1 = 1,870 万光谱'},
 status:'run', facility:'Mayall 4 m + 5,000 光纤（KPNO）', dr:'DR1（公开）；DR2 结果已发、数据未公开', drDate:'DR1: 2025-03-19',
 area:'DR1 ≈9,000 deg²；全巡天设计 14,000 deg²', areaN:14000,
 bands:'3,600–9,824 Å；R≈2,000–5,500（蓝端低、红端高）',
 depth:'选源极限：BGS r<19.5；LRG/ELG 至 z≲1.6；QSO r≲22.5（基于 Legacy 测光）', depthN:0,
 resAng:'光纤 1.5″；光谱 R≈2,000–5,500', nsrc:'DR1 = 1,870 万条光谱（1,800 万+ 独立目标）；DR2(Y3) 分析含 ~1,400 万星系/QSO', nN:7.27,
 sci:'当前最大 3D 宇宙图：BAO/RSD 暗能量（DR2 显示暗能量可能演化）、星系群、强透镜搜寻。',
 links:[['数据门户','https://data.desi.lbl.gov/'],['DR1 文档','https://data.desi.lbl.gov/doc/releases/dr1/'],['DR1 论文 (2503.14738)','https://arxiv.org/abs/2503.14738'],['DESI 官网','https://www.desi.lbl.gov/']],
 paper:['DESI DR1（Abdul-Karim et al. 2025, AJ）','https://arxiv.org/abs/2503.14738'],
 note:'DR1 覆盖 2021-05–2022-06 主巡天。DR2 的 BAO/宇宙学链（Y3 数据）2025-03/10 已公开，但完整 DR2 光谱截至 2026-10 尚未发布——引用时注意区分。'},

{id:'sdssv', name:'SDSS-V', en:'Sloan Digital Sky Survey V（MWM + BHM）', reg:['xspec','gspec','time'],
 spec:'R≈2,000（BOSS 双半球）', rN:2000,
 d:{p:'黑洞测绘+银河系测绘光谱(双半球) + ASPCAP 参数', a:'SDSS-V 门户(SkyServer 兼容)', c:'同一区域多轮回访', v:'DR19 ASPCAP 96.5 万星；DR20 累计千万级'},
 status:'run', facility:'APO 2.5 m + LCO du Pont 2.5 m（双半球）', dr:'DR20（DR19 含 ASPCAP 恒星参数 96.5 万）', drDate:'DR20: 2026-07-30',
 area:'全天无缝选源（Milky Way Mapper / Black Hole Mapper）', areaN:30000,
 bands:'BOSS 光学 3,600–10,400 Å（R≈2,000）；APOGEE H 带 1.51–1.70 μm（R≈22,500）',
 depth:'恒星 I/H≲18–19 视子样本；重复观测获得光谱时域', depthN:0,
 resAng:'光纤 2″（BOSS）/ 2″（APOGEE）', nsrc:'DR20 新增 >200 万条光谱；SDSS 家族累计 ≈500 万+', nN:6.7,
 sci:'银河系测绘（恒星化学动力学时域）+ 黑洞测绘（重复光谱发现变化）+ 器官谱巡天。',
 links:[['SDSS 官网','https://www.sdss.org/'],['数据（SAS）','https://data.sdss.org/'],['SciServer','https://sciserver.org/']],
 paper:['SDSS-V 概览（Kollmeier et al. 2017）','https://arxiv.org/abs/1711.03234'],
 note:'DR18（2024）起转入 SDSS-V。APOGEE 的 ASPCAP 恒星参数/丰度随 DR19+ 持续扩充——银河系化学的首选大样本。'},

{id:'eboss', name:'BOSS + eBOSS', en:'SDSS-III/IV 宇宙学光谱（DR16 终版）', reg:['xspec'],
 spec:'R≈2,000（BOSS）', rN:2000,
 d:{p:'LRG/ELG/QSO 光谱 + 红移表', a:'SDSS SAS/门户(DR16 终版)', c:'单次曝光', v:'≈ 数十万红移(z 0.6–2.2)'},
 status:'done', facility:'APO 2.5 m + 1,000 光纤 BOSS', dr:'DR16（eBOSS 终版）', drDate:'2019-12',
 area:'≈10,000 deg²（北天+三条南带）', areaN:10000,
 bands:'3,600–10,400 Å；R≈2,000',
 depth:'星系 r≲19–21.8（视样本）；QSO 至 g≲22', depthN:0,
 resAng:'光纤 2″', nsrc:'BOSS ≈150 万 + eBOSS ≈50 万新增；累计（含 SDSS-I/II）≈400 万+', nN:6.6,
 sci:'BAO/RSD 宇宙学链条（0.1<z<3.5）的上一代标准；QSO Lyman-α 森林。',
 links:[['DR16','https://www.sdss.org/dr16/'],['eBOSS LSS 论文 (2007.08998)','https://arxiv.org/abs/2007.08998']],
 paper:['eBOSS LSS 终版（Alam et al. 2021, PRD）','https://arxiv.org/abs/2007.08998'],
 note:'已被 DESI 接棒，但历史红移样本与 QSO 光谱仍是标准数据；引用 DR16 之后的 SDSS 光谱注意混入 SDSS-V。'},

{id:'lamost', name:'LAMOST', en:'郭守敬望远镜（低分辨+中分辨光谱巡天）', reg:['gspec'],
 spec:'LRS R≈1,800；MRS R≈7,500', rN:1800,
 d:{p:'LRS 低分辨 + MRS 中分辨光谱 + LASP 恒星参数', a:'LAMOST 官网 DR 页(FITS 批量下载)', c:'每板 1–2 次曝光，每晚多板', v:'DR13 累计 3,082 万条'},
 status:'run', facility:'兴隆 4 m 反射施密特（4,000 光纤，20 deg² 视场）', dr:'DR13 v1.0（2026-03，国内）；全球公开版 DR12 v2.0（2026-09）', drDate:'2026-03',
 area:'北天为主（银道面 + 河外选源区），累计 >1 万 deg² ⚠', areaN:10000,
 bands:'LRS 3,690–9,100 Å（R≈1,800）；MRS 双臂 5,150–5,350 / 6,300–6,800 Å（R≈7,500，非连续）',
 depth:'V≲17–18（LRS 主样本）视视场密度', depthN:0,
 resAng:'光纤 3.3″', nsrc:'DR13：总光谱 >3,082 万（LRS 1,347 万 + MRS 1,736 万）——世界最大光谱库；恒星参数 ~1,000 万组', nN:7.49,
 sci:'银河系运动学+金属丰度大样本、双星、变星、稀有天体；[Fe/H] 极贫金属星搜寻。',
 links:[['LAMOST 官网','http://www.lamost.org/'],['国家天文科学数据中心','https://nadc.china-vo.org/']],
 paper:['LAMOST 巡天概览（Cui et al. 2012 / Zhao et al. 2012, RAA）','https://ui.adsabs.harvard.edu/abs/2012RAA....12.1197C/abstract'],
 note:'注意数据政策：国际公开版滞后约 1–1.5 年（DR13 全球版预计 2027 年下半年）。低分辨适合统计、单星精细丰度需 APOGEE/GALAH 级 R。'},

{id:'gama', name:'GAMA', en:'Galaxy And Mass Assembly', reg:['xspec'],
 spec:'R≈1,600（AAOmega 两臂）', rN:1600,
 d:{p:'红移表 + 22 波段 SED 增值星表 + 星团表', a:'GAMA DR 页直接下载、Data Central', c:'逐区多轮补测至高完备', v:'≈30 万红移'},
 status:'done', facility:'AAT 3.9 m + AAOmega（2dF，400 光纤）', dr:'DR4（公开终版）；DR5 已见诸 2025–26 论文 ⚠', drDate:'2022',
 area:'≈286 deg²（G09/G12/G15 赤道带 + G23 南区）', areaN:286,
 bands:'3,750–8,850 Å 两臂；R≈1,600',
 depth:'主样本 r<19.8（高完备红移）', depthN:0,
 resAng:'光纤 2″', nsrc:'≈30 万红移（>98% 完备）；22 波段 UV–射电 SED 增值星表', nN:5.48,
 sci:'环境与恒星质量关系、星系群表、SED 能量分配——中等红移星系演化的“解剖台”。',
 links:[['GAMA 官网','https://www.gama-survey.org/'],['DR 页面','https://www.gama-survey.org/dr4/']],
 paper:['GAMA 概览（Driver et al. 2011）','https://ui.adsabs.harvard.edu/abs/2011MNRAS.413..971D/abstract'],
 note:'天区与 KiDS/VIKING/DES 重叠、多波段增值产品极丰富；DR5 状态建议直接查官网确认。'},

{id:'devils', name:'DEVILS', en:'Deep Extragalactic VIsible Legacy Survey', reg:['xspec','ir'],
 spec:'R≈1,600（AAOmega 两臂）', rN:1600,
 d:{p:'光谱红移 + 28 波段匹配测光 + VISTA Y 深图', a:'Data Central(查询/下载)', c:'逐场多轮至 90% 完备(Y≈21)', v:'DR1(D10) 新增 5,442 红移'},
 status:'run', facility:'AAT 3.9 m + AAOmega（2dF）；VISTA/VIRCAM Y 深成像（叠 VIDEO）', dr:'DR1（D10/COSMOS 区）', drDate:'2025-12',
 area:'≈4.5 deg²（D10 COSMOS / D02 XMM-LSS / D03 ECDFS）', areaN:4.5,
 bands:'光谱 ≈3,700–9,500 Å（AAOmega 两臂）；选源 VISTA Y',
 depth:'光谱选源 Y<21.2；Y 成像 5σ ≈ 27.2（AB，叠 VIDEO）', depthN:27.2,
 resAng:'光纤 2″', nsrc:'DR1（D10）新增高质量红移 5,442、含外部共 7,946；目标 ≈6 万', nN:3.9,
 sci:'高完备（50%→90% @ Y≈21）星系红移到 z≲1：成对/群环境、质量增长、卫星与并合统计。',
 links:[['DEVILS 官网','https://devils.research.org.au/'],['数据下载（Data Central）','https://datacentral.org.au/']],
 paper:['DR1 论文（2025, MNRAS 544, 3005）','https://arxiv.org/abs/2511.20999'],
 note:'三个经典深场，28 波段 X 射线–射电匹配测光随 DR1 发布；D02/D03 光谱观测仍在进行。'},

{id:'hetdex', name:'HETDEX', en:'Hobby–Eberly Telescope Dark Energy Experiment', reg:['xspec'],
 spec:'R≈800（VIRUS 积分场）', rN:800,
 d:{p:'LAE 盲巡发射线表 + IFU 数据立方', a:'HETDEX 发布页(表/立方)', c:'每指向 3×20 分钟积分 ⚠', v:'PDR1 数十万发射线源 ⚠'},
 status:'run', facility:'HET 9.2 m + VIRUS 78 单元 IFU（≈33k 光纤/次）', dr:'公开：PDR1（+SC1/SC2 源表）；内部 HDR4+ 更大', drDate:'PDR1: 2021-11',
 area:'设计 440 deg²；PDR1 = 86.67 deg²（Spring+Fall）', areaN:440,
 bands:'350–550 nm；R≈700（IFU 盲巡，无选源）',
 depth:'线发射通量 ≈5×10⁻¹⁷ erg/s/cm²（LAE 检出阈）', depthN:0,
 resAng:'IFU 1″ 光纤，3.5″×3.5″ 单元', nsrc:'PDR1 ≈43 万 IFU 观测 / SC1 ≈22 万源（含 5.2 万 LAE、12.4 万 [OII]）', nN:5.34,
 sci:'盲 IFU 光谱：z≈1.9–3.5 LAE 的 BAO、LAE 星系介质的独特样本。',
 links:[['HETDEX 官网','https://hetdex.org/'],['数据（IRSA 镜像）','https://irsa.ipac.caltech.edu/Missions/hetdex.html']],
 paper:['PDR1（Davis et al. 2023, ApJ）','https://ui.adsabs.harvard.edu/abs/2023ApJ...954...39D/abstract'],
 note:'“先光谱后成像”的盲巡天范式，不受测光选源偏差影响；更大规模公开数据（~6 亿光纤光谱量级）已在计划中 ⚠。'},

{id:'4most', name:'4MOST', en:'4-metre Multi-Object Spectroscopic Telescope', reg:['xspec','gspec'],
 spec:'规划：低 R≈1,000 / 高 R≈20,000', rN:1000,
 d:{p:'规划：低/高分辨光谱，5 类巡天并行', a:'规划：ESO Phase 3 档案', c:'巡天期 2026–2031', v:'目标 ≈2,500 万光谱'},
 status:'next', facility:'VISTA 4.1 m + 2,448 光纤（4.3 deg² 视场）', dr:'2025-10 首光；巡天 2026–2031；首个 DR 在巡天开始后', drDate:'首光 2025-10',
 area:'南天（>2,000 万光谱目标）', areaN:20000,
 bands:'LRS 370–950 nm（R≈6,500）；HRS 393–635 nm（R≈18,000）/ 635–950 nm（R≈31,000）',
 depth:'视子巡天（eROSITA 跟踪、4MCRS r<20 等）', depthN:0,
 resAng:'光纤 1.45″', nsrc:'设计 5 年 >2,500 万条光谱', nN:7.4,
 sci:'南天光谱旗舰：eROSITA X 射线源的 Optical ID、银河系盘/晕化学运动学、PFS 级宇宙学红移。',
 links:[['4MOST 官网','https://www.4most.eu/'],['ESO 公告','https://www.eso.org/sci/announcements/sciann17713.html'],['数据产品政策','https://www.4most.eu/cms/operations/dataproducts/']],
 paper:['4MOST 设施（de Jong et al. 2019）','https://ui.adsabs.harvard.edu/abs/2019Msngr.175....3D/abstract'],
 note:'ESO 公共巡天：原始数据实时入 ESO 档案，增值数据定期发布。所有 eROSITA 南天源的地面光谱跟踪基本靠它。'},

{id:'weave', name:'WEAVE', en:'WHT Enhanced Area Velocity Explorer', reg:['xspec','gspec'],
 spec:'低 R≈2,500 / 高 R≈20,000 ⚠', rN:2500,
 d:{p:'低/高分辨多光纤 + IFU 光谱', a:'ESO Phase 3(随 DR 发布)', c:'8 年巡天计划', v:'首个公开 DR 途中'},
 status:'next', facility:'WHT 4.2 m + 1,000 光纤/mIFU（La Palma）', dr:'首光 2022-12；首个公开 DR 待定 ⚠', drDate:'—',
 area:'北天（8 个子巡天：银河系考古、IC 星系、StePS、LOFAR 跟踪等）', areaN:10000,
 bands:'LR 370–960 nm（R≈5,000）；HR ≈406–885 nm（R≈20,000）',
 depth:'视子巡天（如 StePS 红移 0.3–0.8 星系）', depthN:0,
 resAng:'光纤 1.3″/2.6″', nsrc:'设计 1,200 夜 ≈1,200–1,500 万光谱', nN:7.2,
 sci:'北天光谱补位：Gaia 选源的银河系考古 + WEAVE-LOFAR 射电星系 ID + 星族光谱。',
 links:[['ING WEAVE（仪器）','https://www.ing.iac.es/Astronomy/instruments/weave/'],['设施论文 (2203.02026)','https://arxiv.org/abs/2203.02026']],
 paper:['WEAVE 设施（Jin et al. 2024, MNRAS）','https://arxiv.org/abs/2203.02026'],
 note:'巡天科学自 2023 起运行、首批科学结果 2024 发表；公开数据发布节奏盯 ING 档案（astro.ing.iac.es）。'},

{id:'vipers', name:'VIPERS', en:'VIMOS Public Extragalactic Redshift Survey', reg:['xspec'],
 spec:'R≈210（VIMOS LR）', rN:210,
 d:{p:'红移 + 光谱 + CFHTLS 测光(PDR-2 全量)', a:'CDS VizieR、LAM VO 光谱服务', c:'每区 1–2 轮', v:'≈9 万红移'},
 status:'done', facility:'VLT 8.2 m + VIMOS（多狭缝）', dr:'PDR-2（最终版）', drDate:'2018',
 area:'≈24 deg²（CFHTLS W1+W4）', areaN:24,
 bands:'3,600–8,700 Å（R≈210）',
 depth:'选源 I(AB)<22.5（0.5≲z≲1.2）', depthN:22.5,
 resAng:'1″ 狭缝', nsrc:'≈86,775 条可靠红移（全量 ≈9 万）', nN:4.94,
 sci:'DESI 之前 z~1 大尺度结构最大光谱样本：成团性、宇宙学约束、环境与星系特性。',
 links:[['PDR-2（CDS）','https://cdsarc.cds.unistra.fr/viz-bin/cat/J/A+A/609/A84'],['光谱服务（LAM）','https://vo.lam.fr/vipers_dr2/q/web/info']],
 paper:['PDR-2 论文（Scodeggio et al. 2018）','https://arxiv.org/abs/1611.07048'],
 note:'VLT 公共巡天经典遗产；与 CFHTLS 测光配套，z~1 统计仍常用。'},

{id:'pfs', name:'PFS', en:'Subaru Prime Focus Spectrograph（PFS-SSP）', reg:['xspec'],
 spec:'低 R≈300–700 / 中 R≈6,000（三臂）⚠', rN:600,
 d:{p:'将发布：蓝/红/NIR 三臂同时光谱', a:'Subaru/NAOJ(随 SSP 发布)', c:'2025–2030 巡天(已全面运行)', v:'目标 ≈400 万'},
 status:'run', facility:'Subaru 8.2 m 主焦点（2,384 光纤，1.3° 直径视场）', dr:'SSP 巡天 2025-04 开始；尚无公开 DR', drDate:'首光 2025-09',
 area:'目标 ≈1,400–2,400 deg²（与 Rubin 天区重叠）', areaN:2000,
 bands:'三臂 3,800–12,600 Å 单次覆盖（低分辨 + 可见中分辨）',
 depth:'目标 i≲23.5 星系（视项目而定）', depthN:0,
 resAng:'光纤 ≈1.1″', nsrc:'目标 ≈400 万光谱（星系+恒星）', nN:6.6,
 sci:'Rubin/LSST 的光谱主力：单次曝光覆盖至 1.26 μm，BAO/暗能量 + 银河系晕考古。',
 links:[['官网','https://pfs.naoj.org/'],['运行状态页','https://subarutelescope.org/Instruments/PFS/status.html']],
 paper:['PFS 现状（2026, arXiv）','https://arxiv.org/html/2606.14012v1'],
 note:'2025-04 首 SSP 观测、2025-09 官宣首光、2026-03 全面运行；DR1 随巡天推进发布。'},

{id:'moons', name:'MOONS', en:'VLT Multi-Object Optical and Near-infrared Spectrograph', reg:['xspec','ir'],
 spec:'R≈300 / 6,600 / 20,000 三档 ⚠', rN:300,
 d:{p:'规划：0.6–1.8 μm 千光纤多目标光谱', a:'ESO 档案(随 GTO/大项目)', c:'首光 2026 夏，随后巡天', v:'规划百万级'},
 status:'next', facility:'VLT 8.2 m Nasmyth（1,000 光纤，≈500 arcmin² 视场）', dr:'首光 2026 夏；巡天即将展开', drDate:'2026 夏（首光）',
 area:'规划数千 deg²（GTO + 大科学项目）', areaN:0,
 bands:'0.64–1.8 μm 三通道同时（低/中/高分辨 R≈300–20,000 ⚠）',
 depth:'目标 H≲22 星系（视项目）', depthN:0,
 resAng:'光纤 1.2″', nsrc:'规划百万级光谱', nN:0,
 sci:'近红外多目标穿尘埃：银核/核球考古（GALACTIC 巡天）、z~1–2 静息星系、宇宙学。',
 links:[['官网','https://vltmoons.org/'],['ESO 仪器页','https://www.eso.org/sci/facilities/develop/instruments/MOONS.html']],
 paper:['首光报道（Cambridge）','https://www.cam.ac.uk/research/news/a-thousand-eyes-on-the-universe-new-uk-led-astronomy-instrument-takes-first-look-into-the-heart-of'],
 note:'首光即瞄银心 ~1,000 星；近红外多目标能力将超越现有所有巡天设施。'},

{id:'2df6df', name:'2dFGRS / 6dFGRS', en:'经典低红移红移巡天', reg:['xspec'],
 spec:'R≈350（2dF/6dF 光栅）', rN:350,
 d:{p:'红移表 + 星系参数(经典)', a:'VizieR/官网表', c:'单次', v:'2dF ≈25 万、6dF ≈12.5 万'},
 status:'done', facility:'AAT 3.9 m 2dF / UKST 1.2 m 6dF', dr:'终版（2003 / DR3 2009）', drDate:'2009',
 area:'2dF ≈2,000 deg² 两条带；6dF 全南天 |b|>10°', areaN:17000,
 bands:'2dF 3,500–8,000 Å（R≈200）；6dF Ca 三重线 8,400–8,850 Å（R≈1,000）',
 depth:'2dF bJ<19.45；6dF K<12.65（近红外选源）', depthN:0,
 resAng:'光纤 2″', nsrc:'2dF ≈25 万红移；6dF ≈12.5 万红移（含本动速度子样本 1.1 万）', nN:5.4,
 sci:'近距宇宙本动量学（6dFv 奇异速度）、2dF-SDSS LRG；历史基准样本。',
 links:[['6dFGS（VizieR）','https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=VII/261'],['2dFGRS（官方）','https://www.aao.gov.au/2dgrs/']],
 paper:['6dFGS 终版（Jones et al. 2009）','https://ui.adsabs.harvard.edu/abs/2009MNRAS.399..683J/abstract'],
 note:'低红移本动/速度场仍常用 6dFv；新工作多被 SDSS/DESI 覆盖，但近红外选源无尘埃偏差这一点独特。'},

/* ---------------- 光谱 · 银河系 ---------------- */
{id:'apogee', name:'APOGEE-2', en:'SDSS 近红外高分辨恒星光谱', reg:['gspec'],
 spec:'R≈22,500（H 带高分辨）', rN:22500,
 d:{p:'H 带高分辨光谱 + ASPCAP 恒星参数/元素丰度', a:'SDSS 门户(SAS 批量)', c:'每源 3–24 次访问 ⚠', v:'≈ 百万星参数'},
 status:'done', facility:'APO 2.5 m + LCO du Pont 2.5 m（双半球，300 光纤）', dr:'DR17（APOGEE-2 终版）；SDSS-V MWM 继续扩充', drDate:'2021-12',
 area:'全天（银盘截面、晕、麦哲伦云）', areaN:30000,
 bands:'H 带 1.51–1.70 μm；R≈22,500',
 depth:'H≲12.8（盘主样本），红化几乎免疫', depthN:0,
 resAng:'光纤 2″', nsrc:'≈66 万恒星光谱；ASPCAP 参数+20 多种元素 ≈50 万星', nN:5.82,
 sci:'穿尘埃的银河系盘化学-运动学剖面、多世代星族、双星；元素丰度大样本之王。',
 links:[['DR17 数据','https://www.sdss.org/dr17/data_access/'],['APOGEE 门户','https://www.sdss.org/dr17/spectro/']],
 paper:['APOGEE-2（Majewski et al. 2017）','https://ui.adsabs.harvard.edu/abs/2017AJ....154...94M/abstract'],
 note:'DR17 为 APOGEE-2 终版；更新样本看 SDSS-V（DR19+ ASPCAP 已 96.5 万星）。H 带对 extinction 不敏感——银盘首选。'},

{id:'galah', name:'GALAH', en:'GALactic Archaeology with HERMES', reg:['gspec'],
 spec:'R≈28,000（HERMES 四通道）', rN:28000,
 d:{p:'光学高分辨光谱 + 30+ 终端元素丰度', a:'Data Central、VizieR', c:'单次曝光(四通道同时)', v:'DR4 91.8 万恒星'},
 status:'run', facility:'AAT 3.9 m + HERMES（400 光纤）', dr:'DR4', drDate:'2024-10-01',
 area:'南天（|b|>10° 为主）', areaN:20000,
 bands:'4 个非连续窗口 4,713–7,887 Å；R≈28,000',
 depth:'V<14 为主（部分 faint 扩展）', depthN:0,
 resAng:'光纤 2″', nsrc:'917,588 恒星（光谱+参数+~30 元素）', nN:5.96,
 sci:'南天太阳邻域高分辨化学空间；与 Gaia 天测组合做“化学标签”银盘考古。',
 links:[['GALAH 官网','https://www.galah-survey.org/'],['DR4 概览','https://www.galah-survey.org/dr4/overview/'],['DR4 论文 (ADS)','https://ui.adsabs.harvard.edu/abs/2025PASA...42...51B/abstract']],
 paper:['GALAH DR4（Buder et al. 2025, PASA 42, e051）','https://ui.adsabs.harvard.edu/abs/2025PASA...42...51B/abstract'],
 note:'DR4 基于十年观测、管线与元素数量大幅升级；非连续窗口设计使其专注 Gaia 视差亮星。'},

{id:'gaiaeso', name:'Gaia-ESO Survey', en:'VLT 大规模公开光谱巡天（已收官）', reg:['gspec'],
 spec:'R≈20,000–47,000（GIRAFFE/UVES）', rN:20000,
 d:{p:'UVES/FLAMES 高分辨光谱 + 终端丰度', a:'ESO 科学档案', c:'星团锚点多次曝光', v:'≈11 万光谱 ⚠'},
 status:'done', facility:'VLT 8.2 m + FLAMES（130 光纤：GIRAFFE/UVES）', dr:'终版（第 5 次/最终数据发布）', drDate:'2023-07（ESO Phase 3）',
 area:'银河系全场+星团（南天为主）', areaN:10000,
 bands:'470–900 nm 多 setup；GIRAFFE R≈16,000–26,000；UVES R≈47,000',
 depth:'视场/星团样本（V≲17–19）', depthN:0,
 resAng:'光纤 1.2″', nsrc:'≈11.5 万条恒星光谱（场星 + 大量疏散星团/球状星团）', nN:5.06,
 sci:'星团为标定锚点的丰度系统；连接 Gaia 运动学与详细化学。',
 links:[['Gaia-ESO 官网','https://www.gaia-eso.eu/'],['ESO Phase 3 发布','https://www.eso.org/sci/observing/phase3/data-releases.html']],
 paper:['Gaia-ESO 终版（Randich et al. 2023, A&A）','https://ui.adsabs.harvard.edu/abs/2023A%26A...673A..36R/abstract'],
 note:'已收官但其星团丰度框架仍是银河系化学标定的参考文献；后续由 4MOST/WEAVE 银河系巡天接棒。'},

{id:'rave', name:'RAVE', en:'RAdial Velocity Experiment', reg:['gspec'],
 spec:'R≈7,500（Ca 三重线区）', rN:7500,
 d:{p:'Ca 三重线区中分辨光谱 + 恒星参数', a:'RAVE 官网/VizieR DR6', c:'单次 ≈10 分钟', v:'≈52.5 万恒星'},
 status:'done', facility:'UKST 1.2 m + 6dF（150 光纤）', dr:'DR6（终版）', drDate:'2020',
 area:'南天（|b|>15° 为主）', areaN:20000,
 bands:'Ca II 三重线 8,410–8,795 Å；R≈7,500',
 depth:'I=8–12（Bright）', depthN:0,
 resAng:'光纤 6.7″', nsrc:'≈52 万条观测（≈45 万恒星，含视向速度+参数）', nN:5.72,
 sci:'Gaia 之前的太阳邻域运动学奠基样本；本星系群并合遗迹（银晕流）。',
 links:[['RAVE 官网','https://www.rave-survey.org/'],['DR6（VizieR）','https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=I/359']],
 paper:['RAVE DR6（Steinmetz et al. 2020, AJ）','https://ui.adsabs.harvard.edu/abs/2020AJ....160...83S/abstract'],
 note:'I 波段选源 + 窄波段 → 速度快、丰度信息有限；如今多作为 Gaia 时代的补充/交叉样本。'},

/* ---------------- 射电 ---------------- */
{id:'lotss', name:'LoTSS', en:'LOFAR Two-metre Sky Survey', reg:['radio'],
 d:{p:'144 MHz 镶嵌图/单场图 + 射电源表', a:'LoTSS 发布页、ASTRON LTA', c:'每指向 8 小时积分', v:'DR3 ≈ 数百万源(北天 88%)'},
 status:'run', facility:'LOFAR（荷兰核心+欧洲台站，HBA）', dr:'DR3', drDate:'2025',
 area:'DR3 = 北天 88%（迄今最大射电巡天）；DR2 = 4,417 deg²', areaN:32500,
 bands:'120–168 MHz',
 depth:'中位 RMS ≈83 μJy/beam（DR2 口径）', depthN:0,
 resAng:'6″（国际台站基线更高）', nsrc:'DR2 ≈440 万源；DR3 千万量级 ⚠', nN:7,
 sci:'低频射电：AGN/星暴计数、射电喷流、磁场（RM 网格候选）、遥远射电星系。',
 links:[['LOFAR 巡天（lofar-surveys.org）','https://www.lofar-surveys.org/'],['DR3 说明（A&A 接收版）','https://www.oa.uj.edu.pl/LoTSS_DR3_AAaccepted']],
 paper:['LoTSS DR3（Shimwell et al., A&A 2025）','https://www.lofar-surveys.org/publications.html'],
 note:'12,950 小时 / 18.6 PB 的十年工程。低频视场做 AGN 瞬变与光深分析时注意长波选源偏差；配套 LoLSS（42–66 MHz）在建。'},

{id:'racs', name:'RACS', en:'Rapid ASKAP Continuum Survey', reg:['radio'],
 d:{p:'全天 888 MHz(+低/中带)图像 + 源表', a:'CASDA(CSIRO ASKAP 档案)', c:'每指向单次 ≈15 分钟', v:'每带 ≈200 万+ 源 ⚠'},
 status:'run', facility:'ASKAP 36×12 m 阵列（PAF 相位阵馈源）', dr:'RACS-low1/2/3 + mid + high（多频段滚动）', drDate:'RACS-high 论文 2025-01',
 area:'全天南 + 北至 Dec≈+49°（≈34,000 deg²）', areaN:34000,
 bands:'low 887.5 MHz / mid 1,367.8 MHz / high 1,655.5 MHz',
 depth:'low 中位 RMS ≈0.2–0.3 mJy/beam ⚠', depthN:0,
 resAng:'≈18–25″（视频段/切片）', nsrc:'low ≈210 万源（DR1 口径）；三频段合计 ~600 万+', nN:6.3,
 sci:'南天射电参考架 + 历元间变源监测；给 EMU/深巡天当浅层底图。',
 links:[['RACS（CSIRO）','https://research.csiro.au/racs/'],['CASDA 数据','https://research.csiro.au/casda/'],['CADC RACS','https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/racs/']],
 paper:['RACS DR1（Hale et al. 2021, PASA）','https://ui.adsabs.harvard.edu/abs/2021PASA...38...58H/abstract'],
 note:'多历元（low1/2/3）本身构成变源数据集；2025 年有自修正正的文章发布——使用旧目录时应用其天测修正。'},

{id:'emu', name:'EMU', en:'Evolutionary Map of the Universe', reg:['radio'],
 d:{p:'943 MHz 连续谱图 + 源表(南天)', a:'CASDA', c:'每场 ≈10 小时积分 ⚠', v:'DR1 数百万源'},
 status:'run', facility:'ASKAP 36×12 m 阵列', dr:'DR1（首版南天图集）', drDate:'2025',
 area:'目标：南天 Dec<+30°（≈30,000 deg²）；DR1 为首块天区 ⚠', areaN:30000,
 bands:'中心 943.5 MHz（带宽 288 MHz）',
 depth:'≈25 μJy/beam RMS（设计）', depthN:0,
 resAng:'≈10–15″（角分辨率）', nsrc:'目标 ≈7,000 万源；DR1 首块区见论文 ⚠', nN:7.85,
 sci:'深南天射电图集：AGN 星系演化、簇内射电遗迹、低面亮度源、惯性参照联网。',
 links:[['EMU 官网','https://emu-survey.org/'],['CASDA 数据','https://research.csiro.au/casda/'],['DR1 论文 (2505.08271)','https://arxiv.org/abs/2505.08271']],
 paper:['EMU DR1 概览（Hopkins et al. 2025, PASA 42, e071）','https://arxiv.org/abs/2505.08271'],
 note:'比 NVSS 深 ~100 倍；与 LSST/EMU 的射电-光学交叉是南天时域的核心组网。DR1 具体面积/源数以论文与 CASDA 为准。'},

{id:'vlass', name:'VLASS', en:'VLA Sky Survey', reg:['radio','time'],
 d:{p:'2–4 GHz 图像(3 轮 epoch) + 快变/暂现表', a:'NRAO 档案(Quicklook + 时域)', c:'每 epoch 全天 ≈18 个月，共 3 轮', v:'每轮 ≈200 万源 ⚠'},
 status:'run', facility:'NRAO VLA（S 波段，2–4 GHz）', dr:'Epoch 1–3 完成 + SE1/SE2 共加；Epoch 4.1 已批', drDate:'Ep3 完成 2024-10；观测延至 2026-02',
 area:'33,885 deg²（Dec > −40°，两天区）', areaN:33885,
 bands:'2–4 GHz（S 波段）',
 depth:'单历元 QL ≈0.12 mJy；三期叠加 ≈0.07 mJy（5σ）⚠', depthN:0,
 resAng:'2.5″（Quick Look 成像）', nsrc:'≈500 万源/历元（QL 目录）⚠', nN:6.7,
 sci:'高频北天时域射电：变源/暂现、AGN 光变、恒星形成星系、偏振巡测。',
 links:[['NRAO VLASS','https://science.nrao.edu/vlass'],['CADC 数据','https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/vlass/']],
 paper:['VLASS（Lacy et al. 2020, PASA）','https://ui.adsabs.harvard.edu/abs/2020PASA...37...28L/abstract'],
 note:'QL 图像精度有限（自校准后更好）；做测光/光变请用单历元 QL 目录并查已知系统误差文档。'},

{id:'nvss', name:'NVSS / FIRST', en:'VLA 1.4 GHz 经典巡天', reg:['radio'],
 d:{p:'1.4 GHz 连续谱图 + 源表(+FIRST 高分辨)', a:'NRAO、VizieR', c:'单次短曝光', v:'NVSS 177 万 + FIRST 94 万'},
 status:'done', facility:'VLA（1.4 GHz）', dr:'终版（1998 / 2015 增补）', drDate:'1998/2015',
 area:'NVSS：Dec>−40° 全天；FIRST：北天 ≈10,000 deg²', areaN:28000,
 bands:'1.4 GHz（L 波段）',
 depth:'NVSS ≈2.5 mJy；FIRST ≈1 mJy', depthN:0,
 resAng:'NVSS 45″；FIRST 5.4″', nsrc:'NVSS ≈180 万源；FIRST ≈100 万源', nN:6.26,
 sci:'射电匹配的“默认底图”（NVSS）与高分辨结构（FIRST）；历史 AGN 样本基石。',
 links:[['NVSS（CfA）','https://sdc.cfa.harvard.edu/nvss/'],['FIRST（STScI）','https://sundog.stsci.edu/']],
 paper:['NVSS（Condon et al. 1998）','https://ui.adsabs.harvard.edu/abs/1998AJ....115.1693C/abstract'],
 note:'深度已被 LoTSS/VLASS/EMU 超越，但 45″ 大束对低面亮度源流量完整性好，交叉匹配仍在大量使用。'},

/* ---------------- X 射线 ---------------- */
{id:'gleam', name:'GLEAM', en:'GaLactic and Extragalactic All-sky MWA survey', reg:['radio'],
 d:{p:'72–231 MHz 20 子带图 + 源表(+GLEAM-X/300)', a:'MWA 公共档案、VizieR', c:'每指向数分钟积分 ⚠', v:'全天表 ≈30.7 万源'},
 status:'run', facility:'MWA 相控阵（西澳）', dr:'全天源表（2022 宽带版）；GLEAM-X DR2 + GLEAM-300（2025）', drDate:'2022 / 2025',
 area:'≈10,400 deg²（Dec<+30°）', areaN:10300,
 bands:'72–231 MHz（20 子带；GLEAM-300 扩至 300 MHz）',
 depth:'RMS 视频段与子带而异（数十 mJy 级）⚠', depthN:0,
 resAng:'≈2′ 波束', nsrc:'全天源表 ≈30.7 万（72–231 MHz）', nN:5.49,
 sci:'最低频全天天空巡天：陡谱/峰值谱射电源、星系团晕、银道面弥漫辐射、低频暂现。',
 links:[['MWA GLEAM 页','https://www.mwatelescope.org/science/galactic-science/gleam'],['GLEAM-X DR2（VizieR）','https://cdsarc.cds.unistra.fr/viz-bin/cat/VIII/113']],
 paper:['宽带源表（2022, PASA 39, 35）','https://ui.adsabs.harvard.edu/abs/2022PASA...39...35H/abstract'],
 note:'GLEAM-X 为扩展阵加深版；GLEAM-300（2025）扩展到 300 MHz。'},

{id:'apertif', name:'Apertif', en:'WSRT 相控阵馈源巡天（1.4 GHz 连续谱 + HI）', reg:['radio'],
 d:{p:'1.4 GHz 连续谱图 + 源表 + HI 21 cm 光谱立方', a:'ASTRON Apertif DR 页 + 档案', c:'每场 ≈1 小时积分 ⚠', v:'连续谱 ≈40 万源 + HI 星系 1–2 万 ⚠'},
 status:'done', facility:'WSRT 14×25 m + Apertif PAF（40 波束，300 MHz 带宽）', dr:'DR1（2022 成像+HI）；DR2 连续谱 + 时域 DR2（最终）', drDate:'DR2: 2023–24 ⚠',
 area:'≈3,500 deg² 北天', areaN:3500,
 bands:'1,210–1,500 MHz 连续谱 + H I 21 cm 谱线',
 depth:'连续谱 RMS ≈ 10–40 μJy ⚠', depthN:0,
 resAng:'波束 ≈13″×27″ ⚠', nsrc:'连续谱 ≈40 万源 ⚠；HI 星系 ≈1–2 万 ⚠', nN:0,
 sci:'HI 气体与星系演化（吸积/卫星剔除）、射电暂现源、连续谱-光学联合统计。',
 links:[['ASTRON 数据页','https://science.astron.nl/telescopes/wsrt-apertif/apertif-data-access/'],['时域 DR2','https://science.astron.nl/telescopes/wsrt-apertif/apertif-data-access/data-releases/apertif-time-domain-dr2']],
 paper:['首个成像释放说明','https://research.chalmers.se/en/publication/533352'],
 note:'WSRT 时代最后的巡天形态；HI 数据经 ASTRON 档案获取。'},

{id:'erosita', name:'eROSITA', en:'SRG/eROSITA 全天 X 射线巡天（德方）', reg:['xray'],
 d:{p:'0.2–10 keV 源表 + 光子事件表 + 工具链', a:'eROSITA-DE 数据中心(表/工具)', c:'每 6 个月全天一遍(设计 8 遍)', v:'eRASS1 ≈92 万源(西半天)'},
 status:'run', facility:'SRG 卫星 eROSITA（L2；7 组 Wolter 光学）', dr:'eRASS1 目录（西银半球）', drDate:'2024-01/02 公开',
 area:'西银半球 ≈20,000 deg²（eRASS1）；俄方东半球数据未公开', areaN:20000,
 bands:'0.2–12 keV（主能段 0.5–2 keV）',
 depth:'0.5–2 keV 探测限 ≈2×10⁻¹⁴ erg/s/cm²（点源，典型）', depthN:0,
 resAng:'≈26–30″（HR）；≈18″（PSF 平均）', nsrc:'≈93 万点源 + 星系团目录（首个宇宙学样本 ≈5,400 簇）', nN:5.97,
 sci:'X 射线全天：星系团宇宙学、AGN 大样本、激变变星/恒星 X 射线源。',
 links:[['eROSITA-DE（MPE）','https://erosita.mpe.mpg.de/'],['eRASS1 目录（VizieR）','https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=IX/58']],
 paper:['eRASS1 主目录（Merloni et al. 2024）','https://ui.adsabs.harvard.edu/abs/2024A%26A...690A.311M/abstract'],
 note:'2022 年起与俄方合作暂停，东半球全天数据公开无时间表；德方 eRASS1（及后续 eRASS）数据与 4MOST/WEAVE 光谱跟踪组合是当前热点。'},

/* ---------------- 时域 ---------------- */
{id:'xxl', name:'XXL', en:'XMM-Newton Large Survey', reg:['xray'],
 d:{p:'X 射线光子表 + 星团/AGN 表 + 多波段增值', a:'XXL 科学数据库(LAM)、XMM 档案', c:'每场 10–40 ks 一次性', v:'≈450 星团 + ≈2.2 万 AGN'},
 status:'done', facility:'XMM-Newton（≈6.7 Ms，XMM 史上最大项目）', dr:'DR1 2016 起；释放随论文滚动更新', drDate:'首版 2016',
 area:'50 deg²（南/北两区各 ≈25）', areaN:50,
 bands:'0.5–10 keV（EPIC pn/MOS）',
 depth:'≈ 数 ×10⁻¹⁵ erg/s/cm²（0.5–2 keV，10 ks 级）⚠', depthN:0,
 resAng:'PSF ≈6″', nsrc:'≈450 星系团 + ≈22,000 X 射线 AGN', nN:4.34,
 sci:'X 射线暗能量约束：最大均匀 XMM 星团计数样本 + AGN 统计。',
 links:[['XXL-N 页面（MPE）','https://www.mpe.mpg.de/XraySurveys/XMM-XXL/index.html'],['INAF XXL 页','https://www.iasf-milano.inaf.it/xxl/']],
 paper:['XXL 综述（2023, arXiv）','https://arxiv.org/html/2301.11196v2'],
 note:'多波段配套（DES/CFHTLS/红外/射电）齐备；数据经 XXL 科学数据库（LAM）获取。'},

{id:'ep', name:'Einstein Probe', en:'爱因斯坦探针 EP（时域软 X 射线）', reg:['xray','time'],
 d:{p:'WXT 全天监测预警 + FXT 跟随光谱/成像', a:'EP 档案(ESA/NAOC，保护期后) + GCN/ATel', c:'WXT 连续监测(轨道节拍重访)', v:'230+ 暂现源(2 年+)'},
 status:'run', facility:'EP 卫星（2024-01 发射）：WXT 广角 + FXT 跟随', dr:'数据档案 2025-12-11 开放（ToO 6 个月 / 常规 1 年保护期）', drDate:'2025-12',
 area:'全天监测（WXT 单帧视场 3,600 deg²）', areaN:41253,
 bands:'软 X 射线 0.5–4 keV（龙虾眼微孔光学）',
 depth:'典型探测限 ≈2×10⁻¹¹ erg/s/cm²（千秒级曝光）⚠', depthN:0,
 resAng:'WXT ≈5′；FXT ≈1′', nsrc:'230+ X 射线暂现源（2 年+：TDE / GRB / 快暂现）', nN:0,
 sci:'时域软 X 射线全景：潮汐瓦解事件、高红移 GRB、X 射线双星爆发、暂现源普查。',
 links:[['ESA Cosmos EP 页','https://www.cosmos.esa.int/web/einstein-probe'],['国内站点（NAOC）','https://ep.bao.ac.cn/']],
 paper:['EP 机载源表论文（2026, arXiv）','https://arxiv.org/abs/2607.17307'],
 note:'中欧合作；暂现源经 GCN/ATel 实时通报，Swift-XRT 有配套跟测页。'},

{id:'ztf', name:'ZTF', en:'Zwicky Transient Facility', reg:['time'],
 d:{p:'g/r 单次图 + 差分警报流 + 光变曲线', a:'IRSA ZTF 服务 + 警报 broker(ALeRCE 等)', c:'每 3 天全天(g/r 交替)', v:'每夜数十万警报 ⚠'},
 status:'run', facility:'Palomar 1.2 m Samuel Oschin + 47 deg² 相机', dr:'滚动发布（DR23/24 一线；DR2 含 >10¹² 测光值）', drDate:'2025–2026（最新版）',
 area:'全天可及（每 3 天覆盖 g/r 一次）', areaN:30000,
 bands:'g r i（+ 窄带：Hα/OIII 等）',
 depth:'单次 5σ r≈20.5', depthN:20.5,
 resAng:'1″/像素；≈2″', nsrc:'警报 ≈100 万/夜；数十亿光变曲线', nN:9.3,
 sci:'超新星、GW/中微子跟踪、小行星、变星巡天——LSST 之前的时域主力。',
 links:[['ZTF 官网（DR 列表）','https://www.ztf.caltech.edu/ztf-public-drs.html'],['IRSA ZTF','https://irsa.ipac.caltech.edu/Missions/ztf.html'],['警报流（Masci et al. 2019）','https://arxiv.org/abs/1902.01827']],
 paper:['ZTF 系统（Bellm et al. 2019, PASA）','https://arxiv.org/abs/1902.01932'],
 note:'数据分公开/合作两部分；实时警报经 ALerRCE / Fink / ANTARES / MARS 分发。2026+ 与 Rubin 并行运行。'},

{id:'tess', name:'TESS', en:'Transiting Exoplanet Survey Satellite', reg:['time'],
 d:{p:'2 分钟/20 秒目标光变 + FFI 全天图像', a:'MAST(SPOC/QLP 管线)', c:'每扇区 27 天凝视(FFI 200 s–30 min)', v:'数千万光变曲线'},
 status:'run', facility:'TESS 4×0.1 m 广角（全天分 26 扇区）', dr:'滚动（Sector 级，FFI 200s/600s）', drDate:'持续更新',
 area:'全天（逐扇区 27 天凝视）', areaN:41253,
 bands:'600–1,000 nm（宽白光）',
 depth:'单帧 ≈15–16 等（1 小时集成 ~18–19）', depthN:16,
 resAng:'21″/像素（大束，需要匹配源）', nsrc:'数千万光变曲线（TESS-SPOC/QLP 等管线）', nN:8,
 sci:'系外行星凌星 + 全天高精度光变（asteroseismology、潮汐瓦解候选）。',
 links:[['MAST TESS','https://archive.stsci.edu/tess/'],['TESS 官网','https://heasarc.gsfc.nasa.gov/docs/tess/']],
 paper:['TESS（Ricker et al. 2015, JATIS）','https://ui.adsabs.harvard.edu/abs/2015JATIS...1a4003R/abstract'],
 note:'21″ 像素 → 混光严重，做恒星光变务必用 Gaia 源表做污染检查。'},

{id:'asassn', name:'ASAS-SN', en:'All-Sky Automated Survey for Supernovae', reg:['time'],
 d:{p:'V/g 光变数据库(Sky Patrol) + 变星/SN 表', a:'asas-sn.osu.edu 直接下载(免费)', c:'全天每晚数次', v:'≈1 亿目标测光'},
 status:'run', facility:'全球 5 站 20 台 14 cm 望远镜（V + g）', dr:'Sky Patrol V2+（滚动实时）', drDate:'滚动',
 area:'全天（每晚数次）', areaN:41253,
 bands:'V（历史）/ g（现行）',
 depth:'单次 ≈ 17.5（V/g）', depthN:17.5,
 resAng:'≈8″/像素', nsrc:'≈1 亿目标测光档案；变星总表 ≈60 万（≈22 万新发现）', nN:8.0,
 sci:'最亮端时域全覆盖：亮超新星、潮汐瓦解事件发现主力、变星大普查。',
 links:[['数据库','https://asas-sn.osu.edu/'],['OSU 主页','https://www.astronomy.ohio-state.edu/asassn/']],
 paper:['变星总表 X（2022, ApJS）','https://arxiv.org/abs/2205.02239'],
 note:'与 ZTF/Rubin 互补的亮端（g<17.5）；数据免费即取、无需申请。'},

{id:'atlas', name:'ATLAS', en:'Asteroid Terrestrial-impact Last Alert System', reg:['time'],
 d:{p:'o/c 差分图像 + 警报流 + ATLAS-VAR 光变表', a:'MAST ATLAS-VAR、fallingstar 警报', c:'可见全天每晚 ≥4 次', v:'1.42 亿恒星 ≥100 次测光'},
 status:'run', facility:'4 站 0.5 m 广视场（夏威夷×2、智利、南非）', dr:'ATLAS-VAR（MAST，470 万变星候选）+ 滚动警报', drDate:'滚动',
 area:'全天可见区（每晚 ≥4 次）', areaN:41253,
 bands:'o（橙）/ c（青）双宽带',
 depth:'单次 30 s ≈ 18.5–19.5', depthN:19.0,
 resAng:'1.86″/像素', nsrc:'1.42 亿恒星 ≥100 次测光；refcat2 ≈10 亿星参考星表', nN:8.15,
 sci:'小行星预警 + 亮暂现源（SN/激变变星/TDE）；高节奏亮端光变曲线库。',
 links:[['官网','https://atlas.fallingstar.com'],['ATLAS-VAR（MAST）','https://archive.stsci.edu/hlsp/atlas-var']],
 paper:['DR1 论文（Heinze et al. 2018, AJ）','https://arxiv.org/abs/1804.02132'],
 note:'2025-07 发现星际天体 3I/ATLAS（首颗星际彗星候选）。'},
];

const TIMELINE = [
 {d:'2024-02', t:'SkyMapper DR4', n:'南天 uvgriz，>150 亿检测', kind:'past', c:'--c-img'},
 {d:'2024-01/02', t:'eROSITA eRASS1 公开', n:'西银半球 93 万 X 射线源', kind:'past', c:'--c-xray'},
 {d:'2024-10', t:'GALAH DR4', n:'91.8 万恒星高分辨光谱', kind:'past', c:'--c-gspec'},
 {d:'2024-11-14', t:'NEOWISE 最终释放', n:'10.6 年、≈21 遍全天 W1/W2', kind:'past', c:'--c-ir'},
 {d:'2024-11', t:'J-PAS EDR', n:'首份 56 波段数据（12 deg²）', kind:'past', c:'--c-img'},
 {d:'2024', t:'DES DR2', n:'六年全量，≈7 亿源', kind:'past', c:'--c-img'},
 {d:'2025-01', t:'Legacy DR10 常用版', n:'>20,000 deg²，28.3 亿源', kind:'past', c:'--c-img'},
 {d:'2025-03-19', t:'DESI DR1 公开', n:'1,870 万条光谱', kind:'past', c:'--c-xspec'},
 {d:'2025-03-19', t:'Euclid Q1', n:'63.1 deg² 深场预览', kind:'past', c:'--c-img'},
 {d:'2025-04', t:'PFS 首次 SSP 观测', n:'Subaru 主焦点光谱仪开巡（2026-03 全面运行）', kind:'past', c:'--c-xspec'},
 {d:'2025-06', t:'Rubin First Look + DP1', n:'ComCam 七视场', kind:'past', c:'--c-time'},
 {d:'2025', t:'LoTSS DR3', n:'北天 88%，最大射电巡天', kind:'past', c:'--c-radio'},
 {d:'2025', t:'EMU DR1', n:'南天 943 MHz 图集首版', kind:'past', c:'--c-radio'},
 {d:'2025', t:'COSMOS-Web DR1', n:'0.54 deg² JWST 全量公开（27.5–28.2 AB）', kind:'past', c:'--c-ir'},
 {d:'2025-10', t:'4MOST 首光', n:'VISTA 2,448 光纤', kind:'past', c:'--c-xspec'},
 {d:'2025-11', t:'UltraVISTA DR6 Legacy', n:'最终版，深度全区均匀', kind:'past', c:'--c-ir'},
 {d:'2025-12', t:'DEVILS DR1（D10/COSMOS）', n:'5,442 条新高质量红移 + 28 波段匹配测光', kind:'past', c:'--c-xspec'},
 {d:'2025-12', t:'VVV/VVVX 最终全量', n:'13 年 ≈1,700 deg² 银河系红外图', kind:'past', c:'--c-ir'},
 {d:'2025-12-11', t:'Einstein Probe 档案开放', n:'WXT/FXT 数据按保护期公开', kind:'past', c:'--c-xray'},
 {d:'2026-02-24', t:'Rubin 正式巡天启动', n:'DR1 数据开始累积', kind:'past', c:'--c-time'},
 {d:'2026-03', t:'LAMOST DR13 v1.0', n:'光谱总数破 3,082 万', kind:'past', c:'--c-gspec'},
 {d:'2026-06-24', t:'Euclid Q2', n:'银核微透镜深场', kind:'past', c:'--c-img'},
 {d:'2026-06-27', t:'Rubin DP2', n:'主巡天早期数据', kind:'past', c:'--c-time'},
 {d:'2026-07-30', t:'SDSS-V DR20', n:'新增 >200 万光谱', kind:'past', c:'--c-xspec'},
 {d:'2026-08', t:'Legacy DR11', n:'3/4 全天，≈40 亿源', kind:'past', c:'--c-img'},
 {d:'2026-09', t:'Roman 发射 🚀', n:'2.4 m 红外空间望远镜', kind:'past', c:'--c-ir'},
 {d:'2026 夏', t:'MOONS 首光', n:'VLT 千光纤近红外光谱仪', kind:'past', c:'--c-xspec'},
 {d:'2026-11-12', t:'Euclid DR1-Foundation', n:'首半年宽场数据', kind:'future', c:'--c-img'},
 {d:'2026-12', t:'Gaia DR4（预计）', n:'66 个月，130+ 数据产品，历元天测/测光', kind:'future', c:'--c-astro'},
 {d:'2027 年中', t:'Euclid DR1 完整版', n:'一年完整宽场', kind:'future', c:'--c-img'},
 {d:'≈2027', t:'Rubin DR1', n:'首年 18,000 deg² 级数据', kind:'future', c:'--c-time'},
 {d:'2027', t:'CSST / Xuntian 发射（计划）', n:'17,500 deg² 多色+光谱', kind:'future', c:'--c-astro'},
 {d:'2026–2031', t:'4MOST 巡天期', n:'2,500 万光谱目标累积；WEAVE 首个公开 DR 亦在途中', kind:'future', c:'--c-xspec'},
];

const GUIDE = [
 {icon:'🌌', t:'银河系结构与运动学', p:'需要视差/自行/历元信息的一切工作。DR4 前用 DR3 + LAMOST 视向速度；DR4（2026-12）将解锁历元天测。', picks:['Gaia','LAMOST','SDSS-V']},
 {icon:'⚗️', t:'银河系化学丰度/考古', p:'高分辨精丰度用 APOGEE（H 带、穿尘埃）与 GALAH；大样本统计用 LAMOST；星团锚点用 Gaia-ESO；核球/内盘穿尘埃等 MOONS 巡天（2026 首光）。', picks:['APOGEE-2','GALAH','Gaia-ESO','LAMOST','MOONS']},
 {icon:'🛰️', t:'近邻宇宙 / 矮星系与卫星', p:'DELVE 最深广域（DR3 含 DES Y6）配 Gaia 自行剔除前景；南天补 DES / S-PLUS 窄带；核球区穿尘埃用 VVV 红外。', picks:['DELVE','Gaia','DES','S-PLUS','VVV']},
 {icon:'🕸️', t:'大尺度结构 / BAO / 暗能量', p:'DESI DR1 是当前最大公开样本；历史对照用 eBOSS；LAE 盲巡看 HETDEX；未来南天加 4MOST，北天 Subaru PFS 已开巡（2025-04）。', picks:['DESI','BOSS + eBOSS','HETDEX','PFS','4MOST']},
 {icon:'🔭', t:'深场成像 / 弱引力透镜', p:'最深地面 HSC；南天 DES/KiDS；空间像质 + NIR 用 Euclid；深场近红外叠加 UltraVISTA；JWST 级看 COSMOS-Web；2027 后 Rubin DR1 全面接管。', picks:['HSC-SSP','DES','KiDS','Euclid','UltraVISTA','COSMOS-Web','Rubin / LSST']},
 {icon:'🗺️', t:'全天交叉匹配底图', p:'光学：Legacy DR11（叠加最全）/ PS1（北）/ SkyMapper（南）；红外：2MASS+WISE；紫外：GALEX。', picks:['DESI Legacy','Pan-STARRS PS1','SkyMapper','2MASS','WISE','GALEX']},
 {icon:'💥', t:'AGN 与活动星系', p:'WISE 中红外选源 + eROSITA/XXL X 射线 + 射电（LoTSS/VLASS/EMU）+ DESI/SDSS 光谱红移；潮汐瓦解看 Einstein Probe。', picks:['WISE','eROSITA','XXL','LoTSS','DESI','Einstein Probe']},
 {icon:'⏱️', t:'时域 / 暂现源 / 变星', p:'亮端（<17.5 等）ASAS-SN 全天 + ATLAS（o/c 双色，18.5–19.5）；中等深度 ZTF（r≈20.5，3 天节奏）+ Gaia + TESS；红外时域翻 NEOWISE 光变；2026+：Rubin 警报流。', picks:['ASAS-SN','ATLAS','ZTF','Gaia','TESS','NEOWISE','Rubin / LSST']},
 {icon:'📡', t:'射电星系 / 星团遗迹', p:'最深：LoTSS DR3（低频、北天 88%）；南天 EMU；高频分辨 2.5″ 用 VLASS；超低频（72–300 MHz）南天 GLEAM；快速匹配底图 RACS/NVSS；HI 谱线看 Apertif。', picks:['LoTSS','EMU','VLASS','GLEAM','RACS','Apertif','NVSS / FIRST']},
 {icon:'❄️', t:'恒星形成 / ISM / 冰', p:'SPHEREx 全天 0.75–5 μm 光谱（冰吸收）；GALEX+WISE 订 SED；南天 H II 区配 EMU/射电连续谱。', picks:['SPHEREx','GALEX','WISE','EMU']},
 {icon:'🪐', t:'高红移星系（z>3）', p:'HSC 深场+窄带（LBG/LAE）、HETDEX LAE 盲巡、Euclid/Roman NIR 确认；JWST 深场用 COSMOS-Web（0.54 deg²）+ UltraVISTA 底图。', picks:['HSC-SSP','HETDEX','Euclid','COSMOS-Web','UltraVISTA']},
];

const SOURCES = [
 ['Gaia DR4 状态（ESA Cosmos）','https://www.cosmos.esa.int/web/gaia/dr4'],
 ['DESI 数据发布（官方门户）','https://data.desi.lbl.gov/doc/releases/'],
 ['DEVILS 数据（Data Central）','https://datacentral.org.au/'],
 ['DELVE 数据（NOIRLab Data Lab）','https://datalab.noirlab.edu/data/delve'],
 ['J-PLUS / J-PAS（CEFCA 档案）','https://archive.cefca.es/'],
 ['S-PLUS 官方数据页','https://splus.cloud/'],
 ['COSMOS-Web DR（Caltech/IPAC）','https://cosmos.astro.caltech.edu/page/cosmosweb'],
 ['VVV/VVVX 数据发布页','https://vvvsurvey.org/data-releases/'],
 ['PFS 运行状态（Subaru）','https://subarutelescope.org/Instruments/PFS/status.html'],
 ['Einstein Probe（ESA Cosmos）','https://www.cosmos.esa.int/web/einstein-probe'],
 ['ASAS-SN 数据库（OSU）','https://asas-sn.osu.edu/'],
 ['Rubin DP1 / DP2（LSST 文档）','https://dp1.lsst.io/'],
 ['Euclid 数据发布时间线（Caltech）','https://euclid.caltech.edu/'],
 ['Legacy Surveys DR10 说明（官方）','https://www.legacysurvey.org/dr10/description/'],
 ['Legacy DR11 报道（NOIRLab）','https://noirlab.edu/science/news-publications/news/'],
 ['LAMOST 官网与数据政策','http://www.lamost.org/'],
 ['SDSS DR20 发布（sdss.org）','https://www.sdss.org/'],
 ['GALAH DR4（官网 + PASA 论文）','https://www.galah-survey.org/dr4/overview/'],
 ['SkyMapper DR4（arXiv:2402.02015）','https://arxiv.org/abs/2402.02015'],
 ['KiDS DR5（arXiv:2503.19439）','https://arxiv.org/abs/2503.19439'],
 ['DES Y6 测光集（arXiv:2501.05739）','https://arxiv.org/abs/2501.05739'],
 ['HSC-SSP 发布计划（官方）','https://hsc.mtk.nao.ac.jp/ssp/data-release/'],
 ['4MOST 首光（官方新闻）','https://www.4most.eu/cms/news/first_light'],
 ['LoTSS DR3（A&A 接收版说明）','https://www.oa.uj.edu.pl/LoTSS_DR3_AAaccepted'],
 ['EMU DR1（arXiv:2505.08271）','https://arxiv.org/abs/2505.08271'],
 ['RACS / ASKAP（CSIRO）','https://research.csiro.au/racs/'],
 ['eROSITA eRASS1（MPE）','https://erosita.mpe.mpg.de/'],
 ['SPHEREx 数据发布（IRSA）','https://irsa.ipac.caltech.edu/data/SPHEREx/'],
 ['Pan-STARRS 档案（MAST）','https://outerspace.stsci.edu/panstarrs/'],
 ['Roman 任务（NASA）','https://roman.nasa.gov/'],
 ['ZTF 公开数据发布（Caltech）','https://www.ztf.caltech.edu/ztf-public-drs.html'],
];
